### ISSUE TITLE
Deprecate custom ClientRequest and ClientResponse classes

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1038]
I believe everything may be solved by _embeddig_ `ClientSession` instead of adding custom classes.
Keeping current approach exposes too much of internal implementation details to user-level.
These details (`ClientResponse` lifecycle and especially `ClientRequest` existanse) are not documented right now and I don't want to make them public.
Moreover exposing too much prevents deep optimizations because these optimizations breaks API.

Customization support will be removed in an year and half.

Objections?
What needs are not covered by current API without client/response customization?

**Comment by asvetlov** [comment]
@kxepal I see you are using custom responses in aiocoucdb library. 
Do you really need it?

**Comment by kxepal** [comment]
@asvetlov 
Initially, there was a need in them to use custom flow control, but I have a plan to use ijson parser instead of relaying on chunked protocol, especially since it unstable and will be broken in nearest future.

For today, I think I can throw away custom Response class and few more else bits, but not Request one since there I have to define some defaults and the way to correctly serialize body and query parameters and I hardly can imagine any else good place for that logic. 

But actually, I don't see any problem to have an option to allow Request/Response classes customization and keep that feature private. Most users don't need in that, but those who does here is your "dragons ahead" cross line. For instance, there were already breaking changes in ClientRequest class, but it's fine since that is my subclass which was broken because it didn't kept the interface in sync with the parent class.

So I'm fine with removal them from public API land while there would be a way to customize them without much pain.

**Comment by elongbug** [comment]
@asvetlov  Do you mean that just removes comment  about implementing of ClientRequest and ClientResponse on docs/client_reference.rst ????

**Comment by asvetlov** [comment]
Fixed
