### ISSUE TITLE
Move ssl-related params from TCPConnector to request args

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1128]
## Long story short

Now ssl configuration is tightly coupled with `TCPConnector`.

It is not convenient (user should create a connector and pass it into session) and disallows to use the same `ClientSession` for working with different ssl contexts etc.

I think we should move `verify_ssl`, `fingerprint` and `ssl_context` into `ClientSession.request` and `ClientSession.ws_connect` like we have done for `proxy` and `proxy_auth` (see #998).
Current TCPConnector's parameters should be kept as default values which may be overridden by request without any warning/error.

**Comment by magicgoose** [comment]
I think they should not be moved to single requests but to **ClientSession** instead. Multiple requests to the same host+port can reuse connection (or also not reuse, it's statically unknown in general) — https://github.com/aio-libs/aiohttp/blob/3da3a0142e3f8a50c990824ea6d4669643a9fa9e/aiohttp/connector.py#L340 and TLS params are inherently property of the connection, not a HTTP request, so if the user gives different TLS parameters to these requests, that would be very misleading and even non-stable behavior (because it's not known in general if the connection will be reused for a specific request).

@asvetlov do you agree?

**Comment by asvetlov** [comment]
I think if `requests` accepts `verify` and `cert` for every HTTP request call -- why `aiohttp` cannot do the same?

**Comment by magicgoose** [comment]
It can, of course, but I'm not sure if there are real advantages of doing this. But on second thought I see that it's probably fine for user, it would be just a little harder to implement. So, okay…

(at first I thought that there would be also things like which versions of TLS and which ciphers to negotiate with the server, and then there's no meaningful way of changing these constraints for next request with the same connection in general way, other than closing the connection and doing the handshake again, but if this level of control is not going to be allowed, then setting just `verify` and `cert` per request can be defined easily)

**Comment by asvetlov** [comment]
Fixed by #2184
