### ISSUE TITLE
[QUESTION] WebSocketResponse timeout parameter

### ISSUE THREAD

**Issue by Marco-Sulla** [aio-libs/aiohttp#1325]
WebSocketResponse timeout parameter is not documented:
https://aiohttp.readthedocs.io/en/stable/web_reference.html#websocketresponse

What does it do? It's a timeout for websocket **creation** or for websocket **messages**? From source code, it seems it involves websocket closing only.

**Comment by brentspell** [comment]
It appears that the websocket timeout is not being honored during reads.

https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_ws.py#L129

This can be worked around by wrapping the receive*_ call with asyncio.wait_for, but the websocket client should do this internally.

**Comment by fafhrd91** [comment]
Good catch. Question should we use two separate timeout parameters, one for receive and another for close or same for both?

**Comment by brentspell** [comment]
That is a good question. It would probably make sense to use different timeouts for close/receive. However, for backward compatibility, the existing timeout parameter would need to be used for the close timeout, since the current receive timeout is effectively infinite. So, creating a new receive_timeout parameter with a default of None (infinite) would probably be the safest approach.

It would also be useful to allow passing a timeout to the receive_* function that could override the default. This would be analogous to the timeout parameter in ClientSession.request.

**Comment by rutsky** [comment]
Related: https://github.com/KeepSafe/aiohttp/issues/777 , https://github.com/KeepSafe/aiohttp/issues/1024 .

**Comment by fafhrd91** [comment]
added `receive_timeout` to server and client in master
