### ISSUE TITLE
Use aiofiles in static file serving

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1404]
See also #1401

**Comment by AraHaan** [comment]
Wow such bug. I am one for this needing fixed on the event loop. I guesas it is possible (to bypass it( to have a for loop to check if the loop is closed and if so use ``asyncio.new_event_loop()``  also note that sometimes ``get_event_loop()`` can actually return a closed loop and so one can create their own copy of ``get_event_loop()`` that can check if the loop is closed as well. I would recommend that so that way their ``get_event_loop`` actually handles recreating the actual loop.

So yeah that is another possibility to hack bypass such bug.

like one can:

```py
def get_event_loop()
    """"
    Gets an asyncio event loop. And checks to see if it is not closed.
    if the loop is closed this handles crating a new event loop.
    :returns: asyncio Event loop
    """
    loop = asyncio.get_event_loop()
    if loop.is_closed():
        loop = asyncio.new_event_loop()
    return loop
```

That code above is how I personally bypass closed event loops and a ``RuntimeError`` when the event loop is closed.

**Comment by asvetlov** [comment]
@AraHaan 
I don't understand how your comment is related ti the issue.
But silent loop reopening with implicit replacement is definitely an ugly idea.
Please never do this.

**Comment by AraHaan** [comment]
Well unless I use a lib (discord.py) which closes the loop when I dont want it to. Which is the reason I have to hack reopen it as most of the time it goes offline when I cant restart it so it just saves it from not being able to recover from it.

**Comment by asvetlov** [comment]
After a glance on discord.py I see that the library closes loop in `Client.run()` only.
Which is fine if `Client.run()` is called from main function.
But if you need to operate with discord cilen from coroutine you always could use `Client.start()`/`Client.logout()` API.

If a library closes loop -- drop the library and never use it. Or fix the library first.

**Comment by asvetlov** [comment]
Superseded by #3313
