### ISSUE TITLE
Deprecate low-level api from aiohttp namespace

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#1657]
Deprecate 

`aiohttp.HttpMessage`
`aiohttp.Response`
`aiohttp.Request`
 `aiohttp.RawRequestMessage`
`aiohttp.RawResponseMessage`
 `aiohttp.HttpRequestParser`
`aiohttp.HttpResponseParser`
`aiohttp.HttpPayloadParser`

`aiohttp.HttpProcessingError`
`aiohttp.BadHttpMessage`
`aiohttp.HttpBadRequest`
`aiohttp.BadStatusLine`
`aiohttp.LineTooLong`
`aiohttp.InvalidHeader`

`aiohttp.ClientDisconnectedError`

**Comment by AraHaan** [comment]
I agree with this. Also I am thinking of making a Pure C++ wrapper of aiohttp using boost's async stuff if possible so that way people who know how to use aiohttp in python would be able to use cpphttp for C++. However the name might change but for sure some C++ native apps where it is not really effective to use python with their code would see better http support in C++ (Because C++ has slim to none support for http client/server API) and so I plan to finally make one based off of aiohttp. Feel free to contribute to it if you need to. I do have to figure out how to keep it up to par with aiohttp as well.

anyway I will start on the classes and the implementation functions would all return 0 until it gets fully working code much like aiohttp has. The classes and the functions will all have the same names except for the ``__init__`` and some other things.

**Comment by fafhrd91** [comment]
will be removed in 2.1

**Comment by AraHaan** [comment]
ok

**Comment by asvetlov** [comment]
@fafhrd91 what are your exact steps in process of deprecation of library's public names?
How to inform users about deprecation?
Also I suspect that dropping deprecated names in aiohttp 2.1 is too fast for smooth transition period.

**Comment by fafhrd91** [comment]
technically all those names are private, I can not imaging anybody uses those names. 
I think specifically for this set of names dropping early should be safe.

**Comment by fafhrd91** [comment]
maybe except `aiohttp.ClientDisconnectedError`, but we can keep this name longer

**Comment by fafhrd91** [comment]
I do not have strong opinion on this issue. if you think we should keep this names for longer, let's keep them longer.

**Comment by AraHaan** [comment]
tbh if it was me I would have crammed aiohttp into far less modules. But I am not sure if everyone would like it though so yeah. *(Not to mention it is not always a good idea.)*

**Comment by fafhrd91** [comment]
here names that aiohttp2.0 is missing compared to 1.3

```
# we should not export this names in any case
CIMultiDict
CIMultiDictProxy
MultiDict
MultiDictProxy
istr
upstr
multidict

# this are gone after refactoring, and in any case they are too low-level
ParserBuffer
StreamParser
StreamProtocol
parsers

# deprecated
ProxyConnector
HttpPrefixParser

# this are removed, but we can make backward compatibility names
DisconnectedError
ClientHttpProcessingError
HttpMethodNotAllowed
MsgType

# this long time deprecated
delete
get
head
options
patch
post
put
ws_connect

# modules
errors
protocol
web_reqrep
_ws_impl
```

we still export this names for backward compatibility
```
HttpMessage
Request
Response

# http parser, nobody should've use those, to aiohttp specific
# I am not sure if there is any value to keep this names, as api completely changed after
# parser redesign
HttpRequestParser
HttpResponseParser
HttpPayloadParser

# low-level
RawRequestMessage
RawResponseMessage

# this are http parsing specific exceptions and should not escape aiohttp low-level usage
HttpProcessingError
BadHttpMessage,
HttpBadRequest
BadStatusLine
LineTooLong
InvalidHeader

# just backward compatibility
ClientDisconnectedError
ClientTimeoutError
FingerprintMismatch
HttpProxyError
ProxyConnectionError
```

I am not sure about `aiohttp.request(...)`

**Comment by mzfr** [comment]
Hi, I'm new to aiohttp and have some code written using aiohttp low level server that needs to be ported to latest standards. Are there any docs that deal specifically with the porting? What things do we need to change?

**Comment by asvetlov** [comment]
Are you talking about https://docs.aiohttp.org/en/stable/web_lowlevel.html ?
If yes -- you are not affected.
