### ISSUE TITLE
Inconsistent default Content-Type

### ISSUE THREAD

**Issue by tailhook** [aio-libs/aiohttp#184]
When `body` is string or bytes object the aiohttp sets default content type to `application/octed-stream`, but when `body` is `StreamReader` or coroutine or other kind of stream the `Content-Type` is not touched.

I believe automatic `Content-Type` should not be set. But in case it has to, it should at least be consistent.

**Comment by lithammer** [comment]
Taken from RFC 2616, chapter 7.2.1:

> Any HTTP/1.1 message containing an entity-body SHOULD include a `Content-Type` header field defining the media type of that body. If and only if the media type is not given by a `Content-Type` field, the recipient MAY attempt to guess the media type via inspection of its content and/or the name extension(s) of the URI used to identify the resource. If the media type remains unknown, the recipient SHOULD treat it as type `application/octet-stream`.

**Comment by tailhook** [comment]
@renstrom, I'm not sure what you mean. The HTTP spec says "recipient SHOULD", but aiohttp sets header at sender side.

Well, if it's not clear the issue is about the body of POST (and other) requests sent _from client to server_.

**Comment by lithammer** [comment]
Perhaps I misinterpreted. But on the server side, if a client sends a request with a body (regardless of verb) and the `Content-Type` header is missing for whatever reason, the server should interpret it as `application/octet-stream`. That is, unless you wanna implement some kind of guessing algorithm.

I figured you were talking about what a server should do since you mentioned `StreamReader`. But I see now that you explicitly said `aiohttp.client`, my bad...
