### ISSUE TITLE
Break http client code out into separate package

### ISSUE THREAD

**Issue by non-Jedi** [aio-libs/aiohttp#1868]
I'm looking to write an asynchronous http client application, and for that purpose (if you want to use asyncio), aiohttp seems to be the only actively maintained game in town. It would be great if there were something like `aiohttp_client` that I could install as a dependency instead of installing an entire http server just to make some requests.

I haven't looked at the code at all to see how feasible this is, but I thought I'd at least open an issue to get the maintainers thoughts here.

**Comment by AraHaan** [comment]
Or instead make aiohttp be client side only and make server side be 'aiohttp_server'.

Also it is because of python 3.5+ and aiohttp that I eventually want to make my own mmo or something in python. Bot the client and server side of things. But even then the 'server' would have to be cheaply (preferably free) cotton if possible.

And I plan to make it use OpenGL for 3D models and stuff so yeah (that itself needs an c python extension module).

**Comment by fafhrd91** [comment]
this won't happen. aiohttp share 30-40% of code between client and server, and client is more code than server. there is no real reason to split package.
