### ISSUE TITLE
[discuss panel] Formalizing release schedule

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#1917]
@balloob asked me about our release schedule.
Right now we have not it at all.
Perhaps it's not bad -- we live with it for years.

But people want to be informed about new changes in aiohttp and be prepared for changes.

I've tried to write the release procedure but squired up.

@balloob please describe your needs.
From my understanding `CHANGES.txt` updates are not good enough, you need to know about work-in-progress tasks ant our plans.

If you have any proposal -- please share it.

**Comment by balloob** [comment]
One of my concerns was that sometimes the reasoning behind decisions can get lost because code is being committed directly to master instead of via a PR. A PR will require at least some form of description. You can still merge it right away, but at least it will be easier to see a small description of why something happened.

Take for example freezing of applications. Now that we met at PyCon and you explained to me the idea of separating out the setup phase and the run phase, I understand it and I think it's a great idea.

**Comment by fafhrd91** [comment]
I don't believe idea with PRs going to work until we get more active developers.

**Comment by balloob** [comment]
With opening PRs I didn't mean that we should add code reviews. You can merge it right away. But having a PR will allow visibility + a potential place to start discussions.

**Comment by argaen** [comment]
+1 on opening (almost) always PRs. Exception should only be for things like:

- Docs
- CI fixes
- Test fixes
- etc...

Any new feature/functionality change should always go in PRs

**Comment by pfreixes** [comment]
+1 to make the PR as a way to go for commit to master, it will give more visibility to the users. Having as a good side effect prioritization. Obviously, the impact at user level might be low till there is really active community using GH. But, seeing only good things at short and middle term.

Another discussion is about the release by itself, will be nice to have a definition of how and when new major, minor and patches releases will be handled. It will help developers - people committing to aiohttp - and users - anyone that uses aiohttp  - to have a clear idea when the train will pass.

**Comment by asvetlov** [comment]
Well, we'll try to make a PR for every significant change.
About release schedule -- we cannot point a calendar date but could support github milestones for tracking pending issues.

**Comment by balloob** [comment]
Thanks, that would be awesome.
