### ISSUE TITLE
[enhancement] Add ability to disable automatic decompression of body

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#1992]
In our library we'd like the ability to disable the automatic decompression of the request body as we need to compare a hash in the headers to the original body.

Right now this doesn't seem to be possible as the HTTP parser creates a DeflateBuffer which will automatically decompress the body.  If guidance is given how this should be achieved I can create a PR and test case.

**Comment by fafhrd91** [comment]
let's split this into two parts

1. add extra parameter to HttpParser, so it can create HttpPayloadParser with compression=None. This should with both python parser and c-extension parser. this should be simple
2. modify client/web api. this is complicated part, because decompression could start before handler get called.

@asvetlov thoughts?

**Comment by asvetlov** [comment]
I believe @thehesiod talks about client API.
It could be done by simple flag in `session.get()` and family.

**Comment by thehesiod** [comment]
I just noticed that if I try a aiobotocore s3 client `get_object` of a key that a `Content-Encoding` metadata set to `gzip`, it's automatically decompressing the body as well, not-good...this means it returns the wrong datatype for an expected operation due to the automatic decompression.  I'll link another bug report to this.

**Comment by thehesiod** [comment]
this PR only handles `ClientResponse`, other functionality can be added in separate PRs

**Comment by thehesiod** [comment]
ok, created PR which resolves this
