### ISSUE TITLE
do we need http pipelining?

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#2109]
@asvetlov @kxepal thoughts?

**Comment by asvetlov** [comment]
Not sure.
On one hand why not if we could support it easy.
On other hand if pipelining requires extra steps from users they never do it.

**Comment by fafhrd91** [comment]
removing pipelining would simplify request handling flow. (some speedup is expected too) 
pipelining requires read/write ordering. I doubt pipelining is in use, especially for python servers.

**Comment by fafhrd91** [comment]
on other hand pipelining help in synthetic benchmarks

**Comment by kxepal** [comment]
I'm not sure about as well. If HTTP/1 pipelining support cause maintenance issues, slows down general HTTP usage and gives only profit in synthetic benchmark, I think there is nothing much to think about. 

It's pretty cool, but not very popular feature for HTTP/1, but it's a core one of HTTP/2. May be move it HTTP/2 implementation if any will happens?

Btw, do we know any aiohttp usage with pipelining in the wild?

**Comment by fafhrd91** [comment]
Pipelining gives nice 25% boost in synthetic tests :)

**Comment by socketpair** [comment]
https://medium.freecodecamp.org/million-requests-per-second-with-python-95c137af319

**Comment by fafhrd91** [comment]
how much code does it actually run? add business logic written in python and some logging, and this thing would show same speed as any other python framework.

**Comment by fafhrd91** [comment]
I added pipelining because of benchmarks :)

**Comment by samuelcolvin** [comment]
I think pipelining is only really used in tests. The mistake it tests/benchmarks allowing it/being too simple. 

For me, remove if it makes code simpler or provides any other speedups.

**Comment by pfreixes** [comment]
I have a proposal for that.

Right now Aiohttp implements HTTP pipelining but this feature is not fully enabled - correct me if Im wrong @fafhrd91. The default concurrence per connection [1] does not allow Aiohttp to process more than one request at a time. 

Having this scenario and taking into account the complexity that this feature adds in terms of code and the low usage in production systems, almost in microservices architectures,  I would propose to reduce the current HTTP pipelining to a more naive implementation that **does not support concurrence in the same connection**.

Why ? 

1) Reduce the codebase and as a result the performance footprint.
2) Give still support for HTTP pipelining for the none happy path and meeting the HTTP 1.1 requirements.

How ?

1) The first PR, just getting rid of the `max_concurrent_handlers` parameter and removing all of the code that preserves the arrival order and allows Aiohttp have more than one concurrent handler executing at a time.

2) The second PR, reduce if its possible the number of layers needed by request to handle the output.

[1] https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py#L96

**Comment by fafhrd91** [comment]
Pipelining is disabled because of benchmarks. On primitive benchmarks pipelining costs about 4-7%

I am fine with removing pipelining, but pipelined request still should be supported with concurrency 1

**Comment by pfreixes** [comment]
Oks, once the pipelining has been simplified using a naive implementation we can move forward to the next steps. @fafhrd91 you suggested that we might get rid of the `StreamWriter` once we have removed the complexity under the hood, my suggestion heads to remove the big fish, the `PayloadWriter`.

Right now Aiohttp needs at least the following three layers to handle the response: an instance of `StreamWriter`, an instance of `PayloadWriter` and finally an instance of `StreamResponse`, derivates of the last two ones are allowed. The idea is to reduce these three layers to just the `StreamResponse` one. My gut feeling says that it's doable, and that would be done making the following changes:

1) Get rid of the superfluous `StreamWriter` and turn the TCP tunning operations as simple functions.
2) Create an `AbstractResponse` as a replacement of the `AbstractPayloadWriter` specifying the functions that must be implemented. Basically, write methods.
3) Move the current logic of the write methods that are in the `PayloadWriter` to the current write methods of `StreamResponse`.
4) The `StreamResponse` - once is called the `prepare` method - will use the transport rather than use the `PaylodWriter`. 
5) Derivates as web file response u others must implement only one derivate of the `StreamResponse` class.

This would be the sketch more or less, surely I will face problems that right now I cant see them. Anyway, thoughts @fafhrd91 and @asvetlov ?

**Comment by fafhrd91** [comment]
I do not remember all details, I wrote this code year ago. If you can simplify all three layers to only SessionResponse, that would be great.

Some notes:

* http_xxx.py modules are reused by client and server
* server file response
* stream write is just wrapper for transport, but payload write is actual data encoder

**Comment by asvetlov** [comment]
+1
I support removal of extra indirection levels but we should look on PR with implementation first.
If simplification will require backward incompatible changes -- let's discuss every break separately.

**Comment by fafhrd91** [comment]
I don’t think any breakage will require

**Comment by asvetlov** [comment]
I hope so

**Comment by pfreixes** [comment]
Finally, I decided to go a bit slower taking into account that I could end up having something almost impossible - to hard - to review and also to make my process to change all of this with small iterations that will help us definitely. 

So next MR just get rids the current legacy class `StreamWriter` as @fafhrd91 proposed.

https://github.com/aio-libs/aiohttp/pull/2651

**Comment by pfreixes** [comment]
For now, Im gonna "give up" at that point. Meaning that I won't go deeper to refactor more code, the reason is basically it is getting harder and harder and I need some time for rest regarding this subject.

Beside of that, don't you believe that this issue can be closed? Taking into account that the pipelining support has been maintained but making it simpler having the same expectations.

**Comment by asvetlov** [comment]
Agree
