### ISSUE TITLE
Drop md5 and sha1 fingerprints

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2267]
Should be done in 3.0

**Comment by oleksandr-kuzmenko** [comment]
I can help with this

**Comment by redixin** [comment]
To extract signature hash algorithm we need to use either openssl or cryptography. Core library does not expose this information: https://docs.python.org/3/library/ssl.html#ssl.SSLSocket.getpeercert

@alxpy @asvetlov ideas?

@alxpy are you still interested in this issue?

**Comment by asvetlov** [comment]
We use `getpeercert(binary_form=True)`, everything works fine for years

**Comment by redixin** [comment]
Sorry I misunderstood what exactly is needed. I thought you want to disallow client connections to https servers where md5|sha1 was used to sign certificate by CA.

So you want to disallow sha1|md5 while checking fingerprint as described here?

```python
# Attempt to connect to https://www.python.org
# with a pin to a bogus certificate:
bad_fingerprint = b'0'*64
exc = None
try:
    r = await session.get('https://www.python.org',
                          fingerprint=bad_fingerprint)
except aiohttp.FingerprintMismatch as e:
    exc = e
assert exc is not None
assert exc.expected == bad_fingerprint

# www.python.org cert's actual fingerprint
assert exc.got == b'...'
```

Looks like its enough to raise (instead of warning) something from aiohttp/client_exceptions.py in this piece:

https://github.com/aio-libs/aiohttp/blob/20362c52147fdb6de5839f0bb5275c77691e5f62/aiohttp/client_reqrep.py#L348

Should new exception be created? Like InsecureFingerprintHash(ClientSSLError)

**Comment by asvetlov** [comment]
I think `ValueError` is enough.

**Comment by oleksandr-kuzmenko** [comment]
@redixin yes, I'm  interested in this issue, I'll do it on the weekend
