### ISSUE TITLE
QUIC support

### ISSUE THREAD

**Issue by alex-eri** [aio-libs/aiohttp#2275]
## Long story short

QUIC takes about 30% traffic on my hotspots. Generaly Google Ads. 
It can make little projects faster.

Is there plan to support it?

**Comment by asvetlov** [comment]
What kind of support are you asking about?
Please elaborate.

**Comment by asvetlov** [comment]
After digging into QUIC I would say: it could be nice to support it but we need support HTTP/2 first.
QUIC is UDP based protocol, the implementation might take unpredictable amount of time.
Technically asyncio has UDP support but I expect very many work to implement high level protocol on top of it.
Moreover QUIC might migrate to other well supported standard (remember SPDY vs HTTP/2).
I'm inclining to close the issue, it will not be done in overseable future unless somebody will provide a Pull Request.

**Comment by jlaine** [comment]
FYI I have started an asyncio implementation of QUIC:

https://github.com/aiortc/aioquic

**Comment by asvetlov** [comment]
Cool!
QUIC is not trivial, I wish you the best on this way!

**Comment by webknjaz** [comment]
@jlaine I think I saw a number of Python implementations a few years ago. Why create another one?

P.S. It looks like it's better to collaborate on this with https://github.com/python-hyper and have a sansio-style protocol implementation like other Hyper things (https://github.com/python-hyper/h11 + https://github.com/python-hyper/hyper-h2) so that the protocol part wouldn't be framework-specific.

**Comment by asvetlov** [comment]
@webknjaz 
QUIC is like HTTP/2 but over UDP.
It makes a big difference IMHO

**Comment by webknjaz** [comment]
I do know that. I'm just pointing out that bring-your-own-I/O is a more sustainable approach.
