### ISSUE TITLE
Wheels for PyPy

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#2342]
Now we have a tarball for sources and binary wheels for linux, macosx and Windows.

Would be nice to have a wheel for PyPy and other platforms without Cython support.
Technically we could ship a pure Python wheel without C Extensions but I not sure what version `pip` will choose: pure python or binary one for supported platform.

The issue needs more investigation.

**Comment by webknjaz** [comment]
I think we're going to postpone this till OS X stuff is a bit more stable. Feel free to assign this issue to me.

**Comment by asvetlov** [comment]
sounds good

**Comment by edmorley** [comment]
Hi! I don't know if this is expected or not, however for the 2.3.8 release there is only a manylinux1 wheel for Python 3.4, and not for Python 3.5/3.6:
https://pypi.python.org/pypi/aiohttp/2.3.8

(Compare to 2.3.7 which had many more uploaded wheels: https://pypi.python.org/pypi/aiohttp/2.3.7)

**Comment by webknjaz** [comment]
Hi Ed,

It's not related to this issue. However, you are right: it is expected that
all wheel/distro combinations become available.
Maybe the CI wasn't able to make it. I'll need some time to check this.


--Sviatoslav.

Sent from my phone, please pardon any typos.

On Jan 16, 2018 12:44, "Ed Morley" <notifications@github.com> wrote:

Hi! I don't know if this is expected or not, however for the 2.3.8 release
there is only a manylinux1 wheel for Python 3.4, and not for Python 3.5/3.6:
https://pypi.python.org/pypi/aiohttp/2.3.8

(Compare to 2.3.7 which had many more uploaded wheels:
https://pypi.python.org/pypi/aiohttp/2.3.7)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/aio-libs/aiohttp/issues/2342#issuecomment-357922139>,
or mute the thread

**Comment by edmorley** [comment]
Oh sorry I misread the issue title's "PyPy" as "PyPI" 😆

**Comment by asvetlov** [comment]
Thank you for raising the question.
Upload procedure was failed on travis by networking error but travis didn't report it.
I've uploaded files manually

**Comment by webknjaz** [comment]
I think, PR to travis-ci/dpl would be better fix for the issue.
Unfortunately, they don't react to patches fast.


--Sviatoslav.

Sent from my phone, please pardon any typos.

On Jan 16, 2018 13:21, "Andrew Svetlov" <notifications@github.com> wrote:

Thank you for raising the question.
Upload procedure was failed on travis by networking error but travis didn't
report it.
I've uploaded files manually

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/aio-libs/aiohttp/issues/2342#issuecomment-357930747>,
or mute the thread

**Comment by webknjaz** [comment]
JFI travis-ci/dpl#717 finally has been merged, and now Travis raises an error on deploy failure

**Comment by asvetlov** [comment]
Cool!

**Comment by redradist** [comment]
Guys what is the status of aiohttp support ?

**Comment by asvetlov** [comment]
You can install aiohttp on PyPy from the source tarball.
`pip install aiohttp` just works.

**Comment by redradist** [comment]
> 
> 
> You can install aiohttp on PyPy from the source tarball.
> `pip install aiohttp` just works.

@asvetlov 
Okay, thanks !!

Guys, do you know if `aiopg` fixed for PyPy ... ?
I have created few issues ( https://github.com/aio-libs/aiopg/issues/created_by/redradist ), but seems like maintainer of `aiopg` not available at this moment ?

**Comment by asvetlov** [comment]
Cllosing, nobody was interested in the issue for 3 years
