### ISSUE TITLE
The plan for 0.15 release

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#249]
We may make 0.14.2 to fix urgent issues, but I'd like to make a plan for upcoming 0.15 release.

New Year holidays are gone, I'll probably cannot spend too much time to aiohttp.

I would to concentrate on proving the middleware concept by implementing middlewares for session and CORS.

Transplanting security from https://github.com/aio-libs/aiorest/blob/master/aiorest/security.py is also very interesting task.

We need for WebSocketClient in `aiohttp.client` at least for providing the easy way to test our server-side web sockets for our users.

Checking WebSocket implementation by http://autobahn.ws test suite would be very useful. 

I would like to fix #248 (multi-language support URL) not only in `wsgi` but in `aiohttp.web` also.

Pyramid has very strong support for non English URLS, we should do the same.

aiohttp.client has very poor support for file uploading and `multipart-data` at all -- @kxepal has some idea how to improve the current state -- please do.

My wishlist is done.

Any help is very appreciated.

We probably will not finish the whole list on 0.15 release but we should close as many issues as we can do.

**Comment by fafhrd91** [comment]
Basic template support
Paste deploy templates
Tutorial like high level docs for .web
More complex predicate system for url dispatcher?
Application level compression settings
We need to decide how we are going to add new functionality to .web, it is
already big

**Comment by imbolc** [comment]
+1 to "more complex predicate system for url dispatcher". It's a very frequent case to get integer variable from url. For now i'm using tornago-like helper for this: https://gist.github.com/imbolc/0deb6a5fad8fab4c678c

**Comment by lorien** [comment]
Hello guys. I want to help. I can work on some task. I am not familiar much with asyncio/aiohttp but I can learn :) If somebody could point me on task to do I'll try to do it.

**Comment by asvetlov** [comment]
Hi @lorien Glad to see you here!

Implementing websocket client would be very nice (and simple enough for starters) addition to aiohttp. I can elaborate desired design if needed.

**Comment by lorien** [comment]
@asvetlov Yes, I can work on this task. Desired design would be helpful because I have too few experience with aiohttp and websockets.

Actually, I have no experience of websockets at all :) I've googled and found that some bitcoin markets provides websocket channels with trading events. That makes some sense to me, I can test that new websocket client on these channels.

**Comment by asvetlov** [comment]
See #265 for client websocket design.

**Comment by fafhrd91** [comment]
We have ws client/server example, so you can validate your client against existing server. And check aiohttp.web for ws response api

Sent from Outlook

On Thu, Jan 29, 2015 at 6:59 AM -0800, "Gregory Petukhov" notifications@github.com wrote:

@asvetlov Yes, I can work on this task. Desired design would be helpful because I have too few experience with aiohttp and websockets.

Actually, I have no experience of websockets at all :) I've googled and found that some bitcoin markets provides websocket channels with trading events. That makes some sense to me, I can test that new websocket client on these channels.

**Comment by ludovic-gasc** [comment]
@asvetlov Some time ago, we've implemented a very small middleware for CORS support.
Could you be interested in for a pull request or `aiohttp_cors` plugin ?
Or publish your source code, I don't care the origin of that, but everybody that will use `aiohttp.web` for WebServices will need that.

**Comment by fafhrd91** [comment]
i'm done with my changes for 0.15 release. anyone wants to include anything else to 0.15 release?

**Comment by fafhrd91** [comment]
releasing

**Comment by fafhrd91** [comment]
released
