### ISSUE TITLE
pytest-aiohttp: compatibility with pytest v3.3.0

### ISSUE THREAD

**Issue by popravich** [aio-libs/aiohttp#2565]
## Long story short

https://github.com/pytest-dev/pytest/issues/2959
Fixture parameters are now immutable, [pytest_plugin.py](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/pytest_plugin.py#L195-L200) need to be updated

**Comment by asvetlov** [comment]
Fixed by #2573

**Comment by argaen** [comment]
Would it make sense to put code into `pytest-aiohttp` package? In cases like this, a new release of aiohttp is needed and not all the users are prepared to upgrade their aiohttp version just to use the latest pytest. 

So for now, either users have to live with this until they upgrade or this could be backported to previous versions. IMO having this separated in `pytest-aiohttp` would make life easier

**Comment by asvetlov** [comment]
`pytest-aiohttp` is tightly coupled with `aiohttp` itself.
Keeping everything in the single code base simplifies testing aiohttp itself and checking that everything is working without problems.
Introduced pitfall requires a new `pytest-aiohttp` release though just to note people that problem is fixed.

Anyway `pytest-aiohttp` provides guarantee for the latest `aiohttp` only (the same policy as for `aiohttp-session` and other libs. Supporting a matrix of compatible versions is nightmare.
