### ISSUE TITLE
Server impl BaseRequest.schema() should use Forwarded/X-Forwarded headers 

### ISSUE THREAD

**Issue by fafhrd91** [aio-libs/aiohttp#2593]
Server impl BaseRequest.schema() should use Forwarded/X-Forwarded header

**Comment by asvetlov** [comment]
Why?

**Comment by fafhrd91** [comment]
Because your local server could run on plain socket, and your proxy can be on https

**Comment by asvetlov** [comment]
Blind trust in `Forwarded`/`X-Forwarded` is insecure, that's why the functionality was changed in aiohttp 2.3

It's possible to override HTTP schema by `new_req = request.clone(scheme='https')` call.
For aiohttp application there is https://github.com/wikibusiness/aiohttp-remotes with several middlewares (both strict/secure and relaxed/unsecure).
We'll move the library into aio-libs after documentation writing.

**Comment by asvetlov** [comment]
aiohttp-remotes moved to aio-libs, aiohttp documentation mentions the library
