### ISSUE TITLE
no way to read response when InvalidHeader error occurs

### ISSUE THREAD

**Issue by nbraem** [aio-libs/aiohttp#262]
There is currently no way to read the response if there is an invalid header, because the http parser raises an InvalidHeader exception. 

Raising is fine if the error prevents the parser from parsing the rest of the http message. Otherwise the http parser should be more forgiving and ignore invalid headers. 

In my case, there's a header with a space before the colon:

```
X-Echo-set-stash JSON-USER-AGENT: "curl/7.37.1"
```

Urrlib3 has no problem with this, and even returns this header with the space.

**Comment by kxepal** [comment]
Strongly -1.

urllib3 allows that because it's based on urllib which is used http.client which is used email.parser to parse HTTP headers. The problem is that email is far more less strict world because of tons of legacy stuff which doesn't follows any RFC and there are different rules applies on the request/response behaviour. For email, client/server must not loose user message, if only it's completely malformed because this is a human communication base unit. For HTTP situation is opposite since users are communicates with programs and repeating requests is a cheap procedure.

Allowing aiohttp violates RFC will cause more hard support and non-oblivious bugs. As an optional, there could be introduced some "HttpPolicy" object which defines how aiohttp should strictly follow the RFC, but I'm sceptical on this. Better fix your server side to return valid HTTP headers.

**Comment by nbraem** [comment]
This is obviously not my server, it's a random server on the internet.

I'm not saying aiohttp should violate RFC, I'm saying raising an exception is problematic for me as the user of this library. Exceptions are generally used for non-recoverable errors. In this case, there are other ways to communicate an RFC violation, e.g. you could throw a python warning, which I can decide to catch or treat as an error etc. Or you could collect invalid http lines for me to inspect, etc.

Imagine I wanted to build a browser in python using aiohttp. If I couldn't render every page that violates RFC because aiohttp raises an exception, it would be a pretty crappy browser.

The thing is, almost every http client library will ignore the header or return it without problem.

**Comment by saghul** [comment]
I think Postel's principle would be in order here: "be strict in what you send and be gentle in what you accept".

**Comment by kxepal** [comment]
@nbraem from my point of view that's unrecoverable error is the the initial server response is malformed. Here you have three options: crash, try to be resilient and ignore malformed parts and try to be smart and try to fix the malformed parts. We're interested in last two in this issue.
1. Try to be resilient means that aiohttp should loose the data when you actually didn't asked about. It's may be ok if such headers carries no sane value, but what if it will be important like `X-Echo-set-stash AUTH TOKEN: "DEADBEEF"`? The way of ignorance will not be able to let you get this header through common public API. In other words, that's unrecoverable error for you in any case. Raising a warnings isn't good idea since if their rate is high they will be just ignored. This leads you to the next option...
2. Try to be smart allows to handle and recover malformed headers, but leads to spec violation with all the following problems.

That's all the choice.

P.S. Browsers isn't good analogy since it uses by users, not developers, and "being user friendly"  requires for a bit different behaviour.

**Comment by nbraem** [comment]
Ok, so here's my use case. I'm implementing a proxy server. It should transparently pass through invalid headers and let the client decide what do with it. 

Being developer friendly, means giving the developer flexibility. Here's an example how mod_proxy in Apache is developer friendly, it gives 3 options to deal with bad headers:
http://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxybadheader

**Comment by kxepal** [comment]
Yes, a parser policy. This could be a possible solution and email module also has such.

For your case you can override `aiohttp.protocol.HttpRequestParser` and `HttpResponceParser` to pass things as-is and put them to `aiohttp.server.ServerHttpProtocol._request_parser` and `aiohttp.client.ClientResponse._response_parser` respectively to apply the custom behaviour. It's all flexible, just not with one-flag-switch.

**Comment by nbraem** [comment]
Ok, thanks, I'll give that a shot!

**Comment by fafhrd91** [comment]
@nbraem new behavior could be `aiohttp.HttpResponseParser` ctor parameter. and ClientResponse could accept custom response_parser as ctor parameter, but that should not be public api.

**Comment by ludovic-gasc** [comment]
It isn't the same use case, but if we could have a parameter to change behaviour, like you have with [str.encode method](https://docs.python.org/3.4/library/stdtypes.html#str.encode) with `errors` parameter, it should be great.

**Comment by asvetlov** [comment]
The issue is more than a year old.
Also I don't see a strong motivation for working with malformed HTTP headers.
I've rejected several requests like this already.

If somebody may propose an elegant and robust solution -- please open a new issue.
