### ISSUE TITLE
Variety of access logging issues

### ISSUE THREAD

**Issue by thehesiod** [aio-libs/aiohttp#2641]
## Issue 1
Looks like duplicate log format names was accidentally introduced: both `%t` and `%T` resolve to `request_time` see https://github.com/aio-libs/aiohttp/blob/master/aiohttp/helpers.py#L293-L299

each one should have a unique name, thoughts?  Perhaps %T[f] + %D should be `request_elapsed[_frac]`
  
another idea is perhaps we should rename this to `_LOG_FORMAT_MAP` for 3.x?
  
## Issue 2
`%t` is not the start time of the request, it's just the time the log entry was created (not meaningful).  I suggest fixing this to be the time the request was received.

## Issue 3
the base `AccessLogger` is not using self in `__init__` so it's impossible for subclasses to replace methods like `_format_t`

# Issue 4
logging of multiple header values doesn't serialize to extras, last one overwrites the others.

**Comment by thehesiod** [comment]
another issue is that %t is not the start time, it's just "now".  I suggest fixing this to be the time the request was received.

**Comment by thehesiod** [comment]
I've created a PR with a rough idea of a fix

**Comment by thehesiod** [comment]
another issue is that the base AccessLogger was not using self in `__init__` so it was impossible for subclasses to replace methods like `_format_t`

**Comment by thehesiod** [comment]
another bug: logging of multiple header values doesn't serialize to extras, last one overwrites the others.

**Comment by asvetlov** [comment]
Let's discuss issues one by one.

1. Log names was modeled after Apache log format: http://httpd.apache.org/docs/current/mod/mod_log_config.html

2. Access Logger was not intended for inheritance, partially for historical reasons. That's why we don't use `self` in init but use class-level caching. The proper solution is moving a logger instantiation from `web.RequestHandler` to `web.Server` -- logger format parsing should be done once on server startup, not on every connection establishment.
We can even rewrite the `AccessLogger` completely from scratch keeping `AbstractAccessLogger` API. It may speed up log generation as well (the best solution is replacing logger with f-strings as shown in https://docs.aiohttp.org/en/stable/logging.html#format-specification).

**Comment by thehesiod** [comment]
@asvetlov 
1. The issue isn't with the log specifiers, it's with the python logging extras key-name, they need to be unique in the dictionary.
2. (actually 3) I'm not ready to re-write/architect the logger, I can revert this change for now

how about issues 2 + 4 ?

**Comment by thehesiod** [comment]
sorry, forgot to sync change for 4
