### ISSUE TITLE
support reuse_port option when creating server

### ISSUE THREAD

**Issue by hubo1016** [aio-libs/aiohttp#2679]
Python supports `reuse_port` socket option when creating server

https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server

With reuse_port you can start multiple processes binding with the same port, easily creating a load-balanced server. While it is possible to start each process on different port, it can be done much easier with `reuse_port` option.

**Comment by asvetlov** [comment]
Could be done by adding `reuse_port` parameter to `TCPSite` and family.
`reuse_address` should be supported as well.

**Comment by pfreixes** [comment]
From my knowledge and tests reuse port is fundamentally broken for epoll

https://idea.popcount.org/2017-03-20-epoll-is-fundamentally-broken-22/

There is a flag that is available since kernel 4.5 that allows you to achieve the same behaviour. Also glibc has  to be at least 2.24. Most of the distributions do not have it.

Also take into account that this is only appliable for new connections which have the worst code path in terms of performance. Most scenarios relay on long live conections to achieve maximum performance.

**Comment by hubo1016** [comment]
@pfreixes Execuse me, I didn't find any relationship between reuse_port option to the link.
The underlying create_server() call in Python `asyncio` supports this option, it should not be any problem to allow user to set it...

**Comment by pfreixes** [comment]
Because of that @hubo1016 

> With reuse_port you can start multiple processes binding with the same port, easily creating a load-balanced server. While it is possible to start each process on different port, it can be done much easier with reuse_port option.

**Comment by hubo1016** [comment]
@pfreixes As far as I know, `reuse_port` does not create duplicated sockets, it creates independent sockets binding on the same port. dup() issues should not be related to this I think?
After all, if underlying Python implementation supports it, then we should support it and leave the choices to users.

**Comment by asvetlov** [comment]
@hubo1016 please prepare a Pull Request

**Comment by hubo1016** [comment]
@asvetlov 
OK, I will try

**Comment by asvetlov** [comment]
Fixed by #2693
