### ISSUE TITLE
no module named 'universaldetector'

### ISSUE THREAD

**Issue by yjqiang** [aio-libs/aiohttp#3135]
omz/Pythonista-Issues#554
I used the aiohttp on Pythonsita(ios) and I installed it with stash(https://github.com/ywangd/stash). For some requests, it works well. However, sometimes it shows "no module named 'universaldetector' ". It should not be my fault, but it is confusing.

**Comment by asvetlov** [comment]
aiohttp has no `universaldetector` module.
I very doubt if your problem is related to the library.

**Comment by cclauss** [comment]
1. [aiottp has a dependency on chardet](https://github.com/aio-libs/aiohttp/blob/master/requirements/ci-wheel.txt#L6).
2. [chardet's main entry point for character detection is universaldetector.py](https://github.com/chardet/chardet/blob/master/docs/how-it-works.rst)

aiohttp used to work flawlessly on Pythonista for iOS but it no longer does because of changes around its chardet dependency.  Are there other aiohttp contributors who use Pythonista?
