### ISSUE TITLE
DeprecationWarning: Inheritance class Session from ClientSession is discouraged

### ISSUE THREAD

**Issue by GHXST01** [aio-libs/aiohttp#3185]
Hey, not really a bug or an issue but I like inheriting from the ClientSession object when creating an API wrapper that has custom logic for requests (such as hashing of payloads) and custom headers etc.

Just wondering why this seems to be depreciated and if there's an alternative.

**Comment by asvetlov** [comment]
aiohttp is not fixed in stone.
To evolve the library smoothly we need to care about backward compatibility.
The very significant pre-requirement for it is keeping public API as small as possible.
That's why aiohttp has no classes dedicated for inheritance by end user except abstract ones.

If you need a custom logic better to create your own `Client` class with all needed methods and embed `ClientSession` into it.

BTW the same design principle is used by asyncio itself.
