### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AlandKarate** [aio-libs/aiohttp#3242]
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03972C70>
```

How to fix that?

**Comment by kxepal** [comment]
How did you get that?

**Comment by webknjaz** [comment]
Hello @AlandKarate,

Please fill in the issue template in order to help us understand what you are reporting. Without that, it's just a list of words.

I have to close this issue as it doesn't contain any useful information. Feel free to create a new one *filling in* answers to all questions in the template.
