### ISSUE TITLE
Reopen #3208

### ISSUE THREAD

**Issue by Swamp-Ig** [aio-libs/aiohttp#3268]
I'm not sure what's happened exactly, but #3208 still seems to be happening for me.

It did work at one point. Not sure what changed exactly.

**Comment by asvetlov** [comment]
Hi, I'm [GitMate.io](https://gitmate.io)!

It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

If you want me to use a different account for triaging your issues, simply create one and log in with it.

**Sit tight!**

**Comment by kxepal** [comment]
@asvetlov ???

**Comment by asvetlov** [comment]
@kxepal I've enabled GitMate.io bot.
Now it is authorized with my credentials.
Let's see how it works before deciding to use or reject it.

**Comment by Swamp-Ig** [comment]
OK the issue is that if you do a HTTP put to my device, the TCP connection goes crazy and the request fails.

The same thing doesn't happen if you use standard non async requests lib.

I've re-coded my library now to just use requests anyhow, since aiohttp won't work.

**Comment by Swamp-Ig** [comment]
[like this](https://github.com/aio-libs/aiohttp/issues/3208#issuecomment-414843394)

**Comment by Swamp-Ig** [comment]
I figured out the issue. The device I was connected to couldn't handle fragmented requests. Will close.
