### ISSUE TITLE
Keep a list of easy issues active

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#3306]
I had a talk with @gyermolenko 
One of his very valuable complains was a high barrier to start aiohttp contributing.

That's true, selecting a trivial issue to start working on is not an easy choice while looking on the issues list.

We have an *easy* label already but nobody assigns the label to new issues (my personal fault).

@aio-libs/committers please help me with the task.
@webknjaz you are very active on the bug tracker, please take care.

**Comment by webknjaz** [comment]
Also:
* [ ] Apply `Hacktoberfest` label to such issues
* [ ] We need to have a culture of leaving easy issues unresolved. When we see something easy we often just go and fix that, so there's actually no chance for newcomer to jump into those and learn how to contribute.

P.S. @asvetlov we at @ansible have a triaging practice: since the volume of issues is tremendously high we have ppl assigned to each day of the week to look through all incoming issues and adjust labels or ping ppl and send replies to simple cases. (well, we actually have a bot which tries to do part of that work before human attention, but still..)
Do you see it possible to adopt some of such practices within @aio-libs?

**Comment by asvetlov** [comment]
@aio-libs is a volunteer-driven organization.
I doubt if anybody can commit issues sorting job for a long period -- but very appreciate any help on issue trackers.
