### ISSUE TITLE
Scheduled tasks in ensure_future are overlapping by the last one

### ISSUE THREAD

**Issue by yutkin** [aio-libs/aiohttp#3316]
Hello! 

I'm trying to add a new handler that use another existing handler for processing multiple requests at once:

```
async def process_multiple_queries(request):
    init_request = request.clone()
    body = await request.json()

    for query in body["queries"]:

        @asyncio.coroutine
        def fake_json(self):
            return query

        # Replace request body on new fake json
        R = init_request.clone()
        R.json = fake_json.__get__(R, Request)

        # Process request in the background task
        asyncio.ensure_future(process_query(R))

async def process_query(request):
    body = await request.json()
    # ... Process body ...
    return web.json_response({"result": "OK"})

```
However, results of all scheduled tasks are equal to the result of the last task, i.e. bodies of all requests that passed to `process_query` are equal to the body of the last scheduled request.

But if I add `asyncio.sleep(5)` after `asyncio.ensure_future(process_query(R))`, all tasks are processed properly and produce different results.

Python 3.6 in Docker CentOS 7.

**Comment by asvetlov** [comment]
Please don't call one web-handler from another.
`request.clone()` is for replacement a request with the modified one, not for forking many requests from the single source. It violates the HTTP protocol basics.

Extract the common functionality into a third async function and reuse it.
Otherwise, you are asking for trouble -- and you've got it!

**Comment by yutkin** [comment]
OK. Thank you.
