### ISSUE TITLE
Ship certificates bundle with aiohttp

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#341]
`requests` library does it.
Maybe we need the same for `aiohttp`?

**Comment by ludovic-gasc** [comment]
It depends who you want to trust: Do you trust more certificates included in your operating system or them provided by the library you use ?
To be really honest with you, it isn't against you, but I trust more Debian developers to maintain a certificates list that a library maintainer, because you have more Debian developers dedicated to do that for the day-to-day job.
See for `requests`, `certifi` hasn't been updated since previous year: https://pypi.python.org/pypi/certifi

However, it should be interesting to have that on operating systems that don't have a certificates repository.

BTW, for now, with aiohttp.client, how the validity of a CA is valided ? Via the operating system ?

**Comment by kxepal** [comment]
I agree with @GMLudo - certificates isn't a simple thing and so as I trust more my distro maintainers than some third-party python library which name I just learned today (it's about certifi). 

Maximum what you can do here is to allow people to provide their own ca_root / cert_path / key_path in order if they want to use some specific certificates, but that's all.

**Comment by fafhrd91** [comment]
-1 for bundling
+1 for ability to customize

**Comment by asvetlov** [comment]
Close the issue, let's continue in #342 
We decided to never bundle certificates with aiohttp library but want to setup custom chain if needed.
