### ISSUE TITLE
how to config http keepalive timeout on server side

### ISSUE THREAD

**Issue by zpoint** [aio-libs/aiohttp#3577]
After google search, I find these pages may be helpful
[HTTP keepalive illustration](https://gist.github.com/asvetlov/0a4e4c40bca14ff797f6e27cfef4220c)
[make_handler](https://docs.aiohttp.org/en/stable/web_reference.html?highlight=keepalive%20timeout) 
I tried the **make_handler** method, it says 

`DeprecationWarning: Application.make_handler(...) is deprecated, use AppRunner API instead`

But I don't find **keepalive_timeout** in **AppRunner**

I am using 
**MAC**
**Python 3.7.2**
**aiohttp 3.4.4**
I wonder If there is a way to manual config http **keepalive timeout** on server side for the latest version?

**Comment by asvetlov** [comment]
Hi. Sorry for the late answer, I'm terribly busy now.
It is a kind of documentation, code duplication, and human laziness problem.
Copy a function arguments over the all call stack is boring, that's why people use `*args` and `**kwargs`.
But it introduces another problem: you don't know what `kwargs` is without looking deeper.  
`AppRunner` accepts `**kwargs` which are passed to `web_protocol.RequestHandler`.
So `AppRunner(..., keepalive_timeout=120)` should work.

I hope it helps.

Please keep the issue open as the reminder.
`RequestHandler` is not documented (and should not be, it is a very deep implementation detail thing).
But the **options** definitely should be documented.

The solution is simple and, well, boring.
`BaseRunner()` should rigorously enumerate all `RequestHandler` options. Documentation for `BaseRunner` should rigorously enumerate them as well.
It allows to don't mention `RequestHandler` in docs but keep the doc and code in sync.

**Comment by zpoint** [comment]
Thanks for your help!
