### ISSUE TITLE
ClientSession timeout arguments may not work as expected

### ISSUE THREAD

**Issue by dcHHH** [aio-libs/aiohttp#4037]
## Long story short

ClientSession timeout arguments may not work as expected, here is the code:

server:
```python
import time

from flask import Flask
app = Flask(__name__)


@app.route('/five_delay', methods=['GET', 'POST'])
def hello_world():
    time.sleep(5)
    return 'Hello, World!'


if __name__ == '__main__':
    app.run(port=5555)
```

client:
```python
import asyncio
from time import time

from aiohttp import ClientSession


async def query():
    async with ClientSession() as client:
        start_time = time()
        res = await client.post('http://127.0.0.1:5555/five_delay', timeout=5)
        print(time() - start_time)
        print(await res.text())


if __name__ == '__main__':
    ioloop = asyncio.get_event_loop()
    ioloop.run_until_complete(query())
```

## Expected behaviour

TimeoutError

## Actual behaviour

5.014163255691528
Hello, World!

## Your environment

aiohttp-3.5.4
Python 3.6.1
macOS Mojave 10.14.6

i have tested requests, curl, httpie and tornado.httpclient.AsyncHTTPClient, all of them are raising timeout error

**Comment by asvetlov** [comment]
aiohttp rounds client timeouts. If the wall clock now is `10:45:05.23` the 5 sec timeout will be scheduled to `round(10:45:05.23 + 5 sec)` = `round(10:45:10.23)` = `10:45:11`.

This is done for the sake of performance, the system operates much smoothly under high load if all *almost-at-the-same-time* timeout events are grouped together.

If you specify 6 secs delay on the server-side you'll get `asyncio.TimeoutError`.
In practice, this behavior doesn't make a very big difference because of the unpredictable delay on the network side. The 1 second maximum error is not such bad.

**Comment by wumpus** [comment]
This information is not in the documentation, and it should be.

**Comment by asvetlov** [comment]
Please fill free to make a pull request
