### ISSUE TITLE
cookie_jar type incorrect

### ISSUE THREAD

**Issue by alandtse** [aio-libs/aiohttp#4043]
## Long story short

cookie_jar is [currently typed](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L895) to return an `AbstractCookieJar`.  However, it is actually a `aiohttp.CookieJar` which is a type of `AbstractCookieJar` now because it has additional functions `load` and `save`. Downstream users of the library will fail in type checking with mypy when they use either function:

Here's the error; the underlying code isn't relevant
```
pipenv run mypy --ignore-missing-imports alexapy
alexapy/alexalogin.py:546: error: "AbstractCookieJar" has no attribute "save"
```

## Expected behaviour

session.cookie_jar typing should be `CookieJar`. 

## Actual behaviour

session.cookie_jar typing is `AbstractCookieJar`

## Steps to reproduce

Write any code with type checking and try to save or load a cookie_jar object.
Run mypy.
## Your environment

N/A

**Comment by asvetlov** [comment]
The type is correct because the attribute can be any `AbstractCookieJar` instance, e.g. `DummyCookieJar`.
`load()` / `save()` are not a part of ABC interface, it is an implementation specific.
To satisfy `mypy` please add `assert isinstance(session.cookie_jar, aiohttp.CookieJar)` before the calling `load()` or `save()`

**Comment by alandtse** [comment]
Ok thanks. Forgot about the DummyCookieJar.
