### ISSUE TITLE
aiohttp.client_exceptions.ClientConnectorError(24, 'Too many open files')

### ISSUE THREAD

**Issue by dianamuradova** [aio-libs/aiohttp#4067]
## Long story short
Getting error aiohttp.client_exceptions.ClientConnectorError(24, 'Too many open files')

Test script, using Python3-
import asyncio
import aiohttp
import ssl

result_json_list = []
async def fetch(session, url):
        async with session.get(url, ssl=ssl.SSLContext()) as response:
        
            return await response.json()

async def fetch_all(urls, loop, conn):
   
    async with aiohttp.ClientSession(loop=loop, connector = conn) as session:
        
        return await asyncio.gather(*[fetch(session, url) for url in urls], return_exceptions=True)
    

#if __name__ == '__main__':
conn = aiohttp.TCPConnector(limit=0)
urls = url_list[:20000]
loop = asyncio.get_event_loop()
all_result = loop.run_until_complete(fetch_all(urls, loop, conn))

## Expected behaviour
Would like to avoid getting this issue and be able to get all files 

## Actual behaviour

After about 200 (some cases 2000) successful files, I get aiohttp.client_exceptions.ClientConnectorError(24, 'Too many open files')

## Steps to reproduce

The code is above 

## Your environment
using python 3.7

**Comment by asvetlov** [comment]
I expect you know what are you doing by disabling the limit (`aiohttp.TCPConnector(limit=0)`).
Otherwise, search for [too many open files](https://www.google.com/search?q=too+many+open+files&oq=too+many+open+files&aqs=chrome.0.69i59j0l4j69i61.4967j0j7&sourceid=chrome&ie=UTF-8) error and how to increase the limit if you really need it.
