### ISSUE TITLE
Add benchmark link to Main(readme) page 

### ISSUE THREAD

**Issue by corporatepiyush** [aio-libs/aiohttp#430]
Could you guys please add a link to a page demonstrating parallel HTTP calls to web app built on top of aiohttp on the main page. It will help many others understand the importance of this framework over Django and Flask.

Thanks,
Piyush Katariya

**Comment by asvetlov** [comment]
Comparing benchmarks for asynchronous code with synchronous one is very delicate.
I may make test where sync version wins easy (just don't do IO).
Or I make the test where async version will be super fast comparing to synchronous.

**Comment by corporatepiyush** [comment]
There has to some way of proving that non blocking connections always wins :)

**Comment by ludovic-gasc** [comment]
@asvetlov You right, however, most of classical use cases, especially in the HTTP world, you need to have IO in the backend, to access to the database, to a webservice...
Moreover, with WebSockets, async pattern fits better.

In the AsyncIO wiki, you have a list of benchmarks: https://github.com/python/asyncio/wiki/Benchmarks
Most are HTTP related benchmarks, you should add a link in the README or doc.

However, people should test by themselves instead to believe religiously in benchmarks ;-)

**Comment by asvetlov** [comment]
@GMLudo please make a PR :)

**Comment by corporatepiyush** [comment]
@asvetlov Do you find this link authentic ?  i really dont understand what is the cause behind "Serialize a object to JSON and return `application/json` response" tests results 
http://klen.github.io/py-frameworks-bench/

@GMLudo, i agree that every web app is unique and one should  have his/her own benchmark suite. But wouldn't it be nice to have it published officially by framework author ?

**Comment by asvetlov** [comment]
The becnhmark shows that Tornado is slower than aoihttp. I don't believe in that. I think it's misconfiguration problem.

> "Serialize a object to JSON and return application/json response" tests results 

that just means "no IO, return response without any blocking operations".

**Comment by kxepal** [comment]
cc @klen 

P.S. Imho, such benchmarks are evil due to synthetic nature: in real people should check own real use cases and business logic (which is the main bottleneck of everything for all time) that stands behind the framework. Everyone will get here different numbers.

**Comment by ludovic-gasc** [comment]
@asvetlov I'll do that ;-)
About Tornado, I shouldn't be sure as you: I've observed some differences, especially when you use localhost and when you use a physical wire between two servers: Tornado wasn't the best in all use cases, even if, it's often better.

 @corporatepiyush You have two issues with this approach:
1. Interest conflict between the author and be impartial in benchmarks: I know very well this issue, I have that with API-Hour benchmarks: Even if I'm not the AsyncIO author nor aiohttp, it's in my "interest" to have good values. However, I've published that because nobody else seems to be interested to measure that, certainly because to avoid to have open conflicts with some Pythonists.
Because of this, I'm really happy that FrameworksBenchmarks and @klen published also benchmarks, especially benchmark of @klen because I wasn't implied in any sort in this.
2. The author won't have necessary the same usage as his community, it's difficult to publish a representative benchmark that will be useful for everybody.

@kxepal +10. Even if this approach costs a lot, it should be applied when you have a big production where you aren't sure of your future load: with a macro benchmark, you should spot your bottlenecks, more often in your business logic that in technical layers behind.
