### ISSUE TITLE
"RuntimeError: Event loop is closed" when ProactorEventLoop is used

### ISSUE THREAD

**Issue by AndreyMZ** [aio-libs/aiohttp#4324]
## Long story short

When [`ProactorEventLoop`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) is used, the lack of graceful shutdown in aiohttp results in `RuntimeError`. (For comparison, when [`SelectorEventLoop`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.SelectorEventLoop) is used, it results in `ResourceWarning`.) Note that `ProactorEventLoop` is the default event loop on Windows in Python starting from 3.8.

Maybe the root cause of this issue is the same as of #1925. But the impact is higher (`RuntimeError` instead of `ResourceWarning`).

## Steps to reproduce

~~~py
import asyncio
import sys

import aiohttp

async def main():
	async with aiohttp.ClientSession() as session:
		async with session.get('https://example.com/'):
			pass

if __name__ == '__main__':
	if sys.version_info[:2] == (3, 7):
		asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
	asyncio.run(main())
~~~

## Actual behaviour

~~~
sys:1: ResourceWarning: unclosed <socket.socket fd=724, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=6, laddr=('2001:0db8:85a3:0000:0000:8a2e:0370:7334', 19283, 0, 0), raddr=('2606:2800:220:1:248:1893:25c8:1946', 443, 0, 0)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Programs\Python37\lib\asyncio\proactor_events.py:94: ResourceWarning: unclosed transport <_ProactorSocketTransport fd=-1 read=<_OverlappedFuture cancelled>>
  source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000017FAC405048>
Traceback (most recent call last):
  File "C:\Programs\Python37\lib\asyncio\proactor_events.py", line 95, in __del__
    self.close()
  File "C:\Programs\Python37\lib\asyncio\proactor_events.py", line 86, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Programs\Python37\lib\asyncio\base_events.py", line 683, in call_soon
    self._check_closed()
  File "C:\Programs\Python37\lib\asyncio\base_events.py", line 475, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
~~~

## Expected behaviour

No exceptions. Maybe warnings, but no exceptions.

## Your environment

	 
aiohttp (client) version: 3.6.2
Python version: 3.7, 3.8
OS: Windows 10

## Additional information

I do not know any workaround.

A delay before closing the event loop suggested in [the documentation](https://aiohttp.readthedocs.io/en/stable/client_advanced.html#graceful-shutdown) does not help in a bit more complicated example (try to run it several times or add more URLs to the list):

~~~py
import asyncio
import sys

import aiohttp

URLS = [
	# Insert several URLs here, e.g.:
	"https://www.python.org/ftp/python/",
	"https://github.com/python/",
	"https://www.cpan.org/src/5.0/",
	"https://aiohttp.readthedocs.io/",
	"https://example.com/",
]

async def main():
	async with aiohttp.ClientSession() as session:
		await asyncio.wait([fetch(session, url) for url in URLS])
	print("Done.")

async def fetch(session: aiohttp.ClientSession, url: str):
	async with session.get(url):
		print(f"Requested: {url}")

if __name__ == '__main__':
	if sys.version_info[:2] == (3, 7):
		asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
	loop = asyncio.get_event_loop()
	try:
		loop.run_until_complete(main())
		loop.run_until_complete(asyncio.sleep(2.0))
	finally:
		loop.close()
~~~

**Comment by asvetlov** [comment]
The aiohttp master will fix this. Sorry, the change cannot be backported to 3.x branch.

Big enough timeout may saturate the problem. Also, you can ignore all errors on the loop closing as an option.

That's sad that asyncio proactor raises an exception instead of an expected warning. 
You know, asyncio on Windows is underpowered; neither @1st1 nor I am using asyncio on Windows for our daily job.
The fix of asyncio is very welcome, I'm happy to review the proactor's patch if any.

**Comment by HarsheetKakar** [comment]
```
import asyncio
import aiohttp

async def fetch(session, url):
    async with session.get(url) as response:
        return await response.text()

async def harsheet():
    async with aiohttp.ClientSession() as session:
        json = await fetch(session, "<databaseurl>")
        return (json)


async def pyrebase_test():
    async with aiohttp.ClientSession() as session:
        json = await fetch(session, "<databaseurl>")
        return (json)

from pprint import pprint

loop = asyncio.get_event_loop()

group1 = asyncio.gather(harsheet(), pyrebase_test())
results = loop.run_until_complete(group1)
pprint(results)
loop.close()
```
why is this code giving `RuntimeError: Event loop is closed` error?

**Comment by Pythonic-Rainbow** [comment]
This is my temporary solution.
```python
if platform.system() == 'Windows':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

**Comment by AndreyMZ** [comment]
This is not s solution, because `SelectorEventLoop` does not support some features which `ProactorEventLoop` supports. (See <https://docs.python.org/3.8/library/asyncio-platforms.html#windows>.)

**Comment by Pythonic-Rainbow** [comment]
Yes I did not read the topic clearly, I am sorry.

**Comment by thachnv92** [comment]
in <module>
    loop.run_until_complete(process())

**Comment by ianhco** [comment]
Running `asyncio.get_event_loop().run_until_complete(...)` instead of `asyncio.run(...)` doesn't show the error. Is there any difference between them ?

EDIT: Peraphs there is because `run_until_complete` does not close the loop while `asyncio.run` does and calls `_ProactorBasePipeTransport.__del__` where it raises the exception, I've provided a way to handle it in a dirty manner below.

**Comment by ianhco** [comment]
## EDIT (after almost 2 years of fighting with more and more aiohttp bugs)**

As another solution in another issue that is related and more to the root cause, use aiohttp 4.0 or use this code when closing client session https://github.com/aio-libs/aiohttp/issues/1925, monkey patching is not recommended if another solution exists.

## Old monkey patching

I found another solution for this problem if some still having issues with it. This involves directly manipulating the class method itself, it might be dirty in some peoples eyes. This applies to situations where you need to close your loops after a tasks like web apps and other similar situations.
```python
from functools import wraps

from asyncio.proactor_events import _ProactorBasePipeTransport

def silence_event_loop_closed(func):
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        try:
            return func(self, *args, **kwargs)
        except RuntimeError as e:
            if str(e) != 'Event loop is closed':
                raise
    return wrapper

_ProactorBasePipeTransport.__del__ = silence_event_loop_closed(_ProactorBasePipeTransport.__del__)
```

EDIT: You may want to do this only on Windows environment to avoid executing it in production (although `ProactorEventLoop` is not available on Linux, but just in case).
```python
if platform.system() == 'Windows':
    # Silence the exception here.
    _ProactorBasePipeTransport.__del__ = silence_event_loop_closed(_ProactorBasePipeTransport.__del__)
```

**Comment by rbrasga** [comment]
@paaksing Thank you for that. Those errors were bugging me.

**Comment by TKperson** [comment]
@paaksing the code worked like gold. I have been scratching my hair off for days trying to fix this on my discord bot and then I saw this

**Comment by Aran-Fey** [comment]
I don't understand. Why is this still not fixed even though this issue has been closed for almost 1.5 years?

Can't you fix it? Can't you be arsed to fix it? What's going on?

**Comment by paaksing** [comment]
@Aran-Fey This is not a lib specific issue, this is fixed on python 3.9

**Comment by ianhco** [comment]
@Aran-Fey It's fixed for me on 3.9 tho, I honestly don't know the spaghetti behind this, but this is windows specific issue aswell. The workaround that I posted above should solve your issue.

**Comment by Dreamsorcerer** [comment]
> Can't you fix it? Can't you be arsed to fix it? What's going on?

Also, refer to the comment that closed it and try not to be so rude: https://github.com/aio-libs/aiohttp/issues/4324#issuecomment-552850307

**Comment by Aran-Fey** [comment]
@Dreamsorcerer  I've seen that comment. It contains no useful information. "This will be fixed in master"? Clearly not. What am I supposed to take from that comment? There's nothing there except *maybe* the "neither of us uses asyncio on Windows" bit, which doesn't really mean anything either, but kinda sounds like "We don't know how to fix it".

Also, when was I rude?

**Comment by Dreamsorcerer** [comment]
> @Dreamsorcerer I've seen that comment. It contains no useful information. "This will be fixed in master"? Clearly not. What am I supposed to take from that comment? There's nothing there except _maybe_ the "neither of us uses asyncio on Windows" bit, which doesn't really mean anything either, but kinda sounds like "We don't know how to fix it".

Are you reproducing the error on master? If so, then perhaps the issue needs to be reopened, or a new issue made.
If not, the comment said the fix can't be backported to 3.x, meaning that it is probably not fixed in any public release currently.
If you think this is incorrect and the issue can be fixed in 3.x (I have no knowledge about this issue myself), then feel free to provide a fix in a PR.

> Also, when was I rude?

In the comment I quoted, and your messaging still sounds aggressive...

**Comment by Aran-Fey** [comment]
Ah, now I understand. I didn't realize aiohttp had gone 1.5 years without a new release. It's baffling to me that an issue like this would go unfixed for that long, but it's my bad for not confirming if we're still on version 3.x. I assumed the 3.x days were long past, but I should've double-checked.

So to recap: What @paaksing said was wrong; this isn't a python issue, it's an aiohttp issue. And we can't expect a fix before aiohttp v4. Is that correct?

Also, is there an ETA for when we can expect aiohttp v4 to be released?

(P.S. I don't want to get off-topic, and I don't know why you think I sound aggressive, but maybe it helps if you think of my tone as... I don't know... neutral? Deadpan? Emotionless? Something like that.)

**Comment by paaksing** [comment]
@Aran-Fey The fact that you're recapping things so decisively is really bad, there are multiple libraries out there that is having similar issues because of proactor and are patching bandaid fix instead (you can refer the multiple references found under the code I provided), and yes your comments are all the way aggressive. Period.

**Comment by Dreamsorcerer** [comment]
> Ah, now I understand. I didn't realize aiohttp had gone 1.5 years without a new release.

There has not been a 4 release in that time, no. There has been plenty of 3.x releases, which is the current stable branch. 4 is not a priority as far as I can see, but all improvements are made into both master/4 and the current 3.x release branch.

> So to recap: What @paaksing said was wrong; this isn't a python issue, it's an aiohttp issue. And we can't expect a fix before aiohttp v4. Is that correct?

I'm just going by the same info as you, I've not looked into this issue or ever encountered it myself.

> Also, is there an ETA for when we can expect aiohttp v4 to be released?

I'm not really involved with releases, but I'm not expecting it to be anytime soon. Currently, I'm just hoping for the 3.8 release, which contains a number of other fixes I need. If it's an issue for you and the workarounds mentioned don't work for you, then I'd suggest trying master for the time being.

> (P.S. I don't want to get off-topic, and I don't know why you think I sound aggressive, but maybe it helps if you think of my tone as... I don't know... neutral? Deadpan? Emotionless? Something like that.)

Imagine you've given somebody a free gift, but it's not quite perfect for them, and they turn around and say "Couldn't you be arsed to add this?". That comes off as rude. I understand your frustration, but remember everyone is volunteering and mostly people want to work on the things that affect themselves more than other issues (e.g. for this issue, it sounds like a Windows problem, and I doubt any of the core developers are using Windows). So, if you you don't want to fix it yourself, or pay someone else to work on it, just remember to have patience and hope that somebody else will take the initiative.

**Comment by Aran-Fey** [comment]
@paaksing Why is it really bad? What's wrong with my recap? Are you saying it's *both* a python issue *and* an aiohttp issue?

I just want to know what will fix this issue, and when that will happen, because I need that information to decide how to deal with this bug. If a bugfix will be released next week, I'll wait it out. If the bug cannot be fixed before python 3.10, I'll resort to using one of the various workarounds that have been mentioned. This is crucial information, that, as far as I can tell, isn't mentioned anywhere in this thread.

So: What is the cause, and how/when can we expect it to be fixed?

@Dreamsorcerer Thanks for your help.

Like I said, I don't want to get off-topic, but I'll address the "rudeness" thing one last time.

> Imagine you've given somebody a free gift, but it's not quite perfect for them, and they turn around and say "Couldn't you be arsed to add this?". That comes off as rude.

Sure, but that's not what happened. I came across a bug that still existed despite having been reported a long time ago, so naturally I wanted to know why. One possibility I could think of was that it isn't fixable. The other possibility I could think of was that nobody cared to fix it. Both are perfectly valid reasons. I don't *care* why it isn't fixed, I just want to *know*. There's no judgment involved there.

And that's all I'm going to say about that matter. If I still sound aggressive, you'll just have to believe me that it's not intentional. I'm not here to judge or rage or yell, I'm here to obtain information. (Although it hasn't worked out very well so far.)

**Comment by paaksing** [comment]
@Aran-Fey What about reading the comments once again and you'll probably find a fix ? Bashing on an issue before even trying the provided fixes on the comments and making assumptions out of nowhere is really bad and non-professional.

> have patience and hope that somebody else will take the initiative.
@Dreamsorcerer  There is a code snippet on the comments that fixes the issue, it worked to multiple devs either using or not using aiohttp. But I am gonna assume that he didn't even read.

**Comment by admirabilis** [comment]
A Windows error? I also have to use `asyncio.get_event_loop().run_until_complete()` instead of `asyncio.run()` as mentioned by paaksing on Linux, Python 3.9.2.

**Comment by Dreamsorcerer** [comment]
> A Windows error? I also have to use `asyncio.get_event_loop().run_until_complete()` instead of `asyncio.run()` as mentioned by paaksing on Linux, Python 3.9.2.

The bug report is about `ProactorEventLoop`, this appears to only be available on Windows:
https://docs.python.org/3/library/asyncio-eventloop.html?highlight=proactor#asyncio.ProactorEventLoop

Which would suggest that you may be experiencing a different issue.

**Comment by Aran-Fey** [comment]
@paaksing There are no fixes here, only workarounds - if they can even be called that. Silencing an exception is not the same thing as fixing the problem.

If any of the proposed "solutions" had actually fixed the issue, then it would've been merged into aiohttp 3.x a long time ago.

**Comment by paaksing** [comment]
@Aran-Fey It's an exception thrown on loop close, meaning it doesn't impact your code at all, so I don't see why "silencing an exception" is not a fix, as suggested by contributors here you can ignore such exceptions.

If you would play the word game hard enough, then yes, there is no "fix" because the same code on Linux is not throwing anything, so they would have to do extra code just to satisfy windows user to "not see the ignored exception", which that's likely not gonna happen.

Let's be realistic, most production code is deployed on a Linux machine, so you can surely do this:
```python
if platform.system() == 'Windows':
    # Silence the exception here.
```
which won't be executed on Linux. Tested this on multiple production project of mine without issues.

So, what's your perseverance here ?

**Comment by Aran-Fey** [comment]
@paaksing If there's a fix with no downsides, then why haven't the devs used it? Why do you think a "fix" that isn't good enough to be included in aiohttp is good enough to be included in *my* project?

The fact of the matter is that I don't know what's causing the problem, or what could go wrong if I "fix" it incorrectly. Plus, I don't want my library to be responsible for aiohttp's problems.

So I'm not going to apply a bandaid fix I don't entirely understand unless I absolutely have to. And that's what I'm here to find out. *Do* I have to? Or can I expect aiohttp and/or CPython to fix it?

**Comment by ianhco** [comment]
@Aran-Fey
Let me ask you back: **Why would the devs use it if**:
1. It's not their issue.
2. It's not impacting functionality wise.
3. It's not affecting production environment.
?

Also I am not forcing you to include that in your project, you asked for a fix, I gave you a "fix that you said it is not", you still got the golden finger to decide what to do with your project.

**Comment by admirabilis** [comment]
> The bug report is about `ProactorEventLoop`, this appears to only be available on Windows:
> https://docs.python.org/3/library/asyncio-eventloop.html?highlight=proactor#asyncio.ProactorEventLoop
> 
> Which would suggest that you may be experiencing a different issue.

Ah, yes, I get a similar harmless RuntimeError, the message I'm ignoring is "Event loop stopped before Future completed."

**Comment by Dreamsorcerer** [comment]
> > The bug report is about `ProactorEventLoop`, this appears to only be available on Windows:
> > https://docs.python.org/3/library/asyncio-eventloop.html?highlight=proactor#asyncio.ProactorEventLoop
> > Which would suggest that you may be experiencing a different issue.
> 
> Ah, yes, I get a similar harmless RuntimeError, the message I'm ignoring is "Event loop stopped before Future completed."

Feel free to create a new issue with some code which reproduces it. It may just be something you overlooked in your code.

**Comment by NewUserHa** [comment]
see https://bugs.python.org/issue39232

**Comment by ttodua** [comment]
I don't think any of the above posted workarounds are ideal, either silencing the exception (not desirable), or setting `SelectorEventLoopPolicy` (which degrades functionality as mentioned above and [here too](https://stackoverflow.com/questions/67964463/)).

Better workaround might be :
1)  update python to 3.10.6, where the issue seems no longer happening.

or

2) to inject `0.25` sleep in shutdown function, like this, which avoids exception:
```
originalShutdownFunc = asyncio.BaseEventLoop.shutdown_default_executor
async def shutdown_default_executor(arg):
    result = await originalMet(arg)
    await asyncio.sleep(0.25)
    return result

asyncio.BaseEventLoop.originalShutdownFunc = shutdown_default_executor

asyncio.run(your_function) # HERE RUN YOUR ASYNCIO CODE
```

**Comment by ianhco** [comment]
This is apparently fixed on aiohttp 4.0 beta. A more serious issue is involved here, a solid workaround was provided in this comment: https://github.com/aio-libs/aiohttp/issues/1925#issuecomment-708690799
I will edit my previous comments to discourage the use of them.

**Comment by Mark-Jethro** [comment]
how to fix connectionreseterror: [winerror 10054] an existing connection was forcibly closed by the remote host

**Comment by NewUserHa** [comment]
`asyncio.wait()` before that loop closes, or use `loop.run_until_complete` instead of `asyncio.run()`. if remember correctly.

**Comment by waketzheng** [comment]
> I don't think any of the above posted workarounds are ideal, either silencing the exception (not desirable), or setting `SelectorEventLoopPolicy` (which degrades functionality as mentioned above and [here too](https://stackoverflow.com/questions/67964463/)).
> 
> Better workaround might be :
> 
> 1. update python to 3.10.6, where the issue seems no longer happening.
> 
> or
> 
> 2. to inject `0.25` sleep in shutdown function, like this, which avoids exception:
> 
> ```
> originalShutdownFunc = asyncio.BaseEventLoop.shutdown_default_executor
> async def shutdown_default_executor(arg):
>     result = await originalMet(arg)
>     await asyncio.sleep(0.25)
>     return result
> 
> asyncio.BaseEventLoop.originalShutdownFunc = shutdown_default_executor
> 
> asyncio.run(your_function) # HERE RUN YOUR ASYNCIO CODE
> ```

Worked for me with python3.11, but the code is as follows:
```py
import asyncio

origin_shutdown = asyncio.BaseEventLoop.shutdown_default_executor
 
 
async def _shutdown(self):
    await origin_shutdown(self)
    await asyncio.sleep(5)
 
 
asyncio.BaseEventLoop.shutdown_default_executor = _shutdown  # type:ignore
```
