### ISSUE TITLE
Host header should have port 443

### ISSUE THREAD

**Issue by ionling** [aio-libs/aiohttp#4376]
## Long story short

If I access a https website via http tunnel (connect method, `CONNECT www.bilibili.com:443 HTTP/1.1\r\n\r\n`), the request's `Host` header should be `www.bilibili.com:443` not `www.bilibili.com` which `aiohttp` actually does.

For more info,  just see  RFC https://tools.ietf.org/html/rfc7230#section-5.4.

## Expected behaviour

The request's `Host` header should be `www.bilibili.com:443`.

## Actual behaviour

The request's `Host` is `www.bilibili.com`.

## Steps to reproduce

```
session.get('https://www.bilibili.com', proxy='http://localhost:8889')
```

## Your environment

- Manjaro 18.1.13
- Python 3.7.4
- aiohttp client 3.6.2

**Comment by asvetlov** [comment]
The PR is welcome!

**Comment by Purusah** [comment]
Hello, I searched this issue and found that [here](https://github.com/aio-libs/aiohttp/blob/eabc38c41cde887b173c03c625430666b7130c77/aiohttp/client_reqrep.py#L317) aiohttp sets `Host` header with related port. But default port check in [yarn](https://github.com/aio-libs/yarl/blob/0d336ef870fe33794bc06e999891d3c6010b353a/yarl/__init__.py#L336) library assume that 443 port is default. Should it be one more check [inside this function](https://github.com/aio-libs/aiohttp/blob/eabc38c41cde887b173c03c625430666b7130c77/aiohttp/client_reqrep.py#L309) for `https` schema and setting correct port in `Host` header or it can be fixed in yarn?

**Comment by asvetlov** [comment]
Hold on.
Host header for `https://python.org` should be `python.org`, `http://python.org:443` (note: schema is http but port is 443) should generate `Host: python.org:443`. `aiohttp` does it currently.
`curl` does the same.

For `session.get('https://www.bilibili.com', proxy='http://localhost:8889')` the `Host` header should be also `www.bilibili.com` regardless of HTTP proxy usage.

What is the problem?

**Comment by Purusah** [comment]
Ok, sorry, according to your explanation I can't find bug related to issue.

**Comment by asvetlov** [comment]
Closing the issue.
Thanks for attracting attention!
