### ISSUE TITLE
Support Happy Eyeballs from Python 3.8

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#4451]
Starting from Python 3.8 asyncio supports https://tools.ietf.org/html/rfc6555

It allows working better in dual-host configurations.
It would be nice to support it by aiohttp if the feature is available by Python version.
Perhaps passing `happy_eyeballs_delay` and `interleave` to `loop.create_connection()` is enough.

A volunteer is welcome!

P.S.
Ooops, parameters are even not documented by asyncio docs, need to fix it.

**Comment by illia-v** [comment]
> Perhaps passing `happy_eyeballs_delay` and `interleave` to `loop.create_connection()` is enough.

Unfortunately, this is not enough and has no effect because `host` passed to `loop.create_connection()` is always an IP address. That happens because aiohttp translates domain names into IP addresses before calling the method.
https://github.com/aio-libs/aiohttp/blob/8c25b44770e56ee5636d16d65687a732e1545c5a/aiohttp/connector.py#L969-L1025

---

An alternative is implementing the Happy Eyeballs algorithm in the aiohttp library reusing `asyncio.staggered.staggered_race()`.

I would create a method similar to [`loop._connect_sock`](https://github.com/python/cpython/blob/cc02b4f2e810ab524d845daa18bc94df5b092dd8/Lib/asyncio/base_events.py#L930-L964) and use logic similar to [this one](https://github.com/python/cpython/blob/cc02b4f2e810ab524d845daa18bc94df5b092dd8/Lib/asyncio/base_events.py#L1036-L1050) right after determining IP addresses.

Then I'd call `self._wrap_create_connection()` (and subsequently `loop.create_connection()`) with a connected socket as `sock` instead of `family`, `proto`, `flags` and `local_addr`.

There would be a couple of problems though:
* this check would be performed only once for a connection determined by Happy Eyeballs and if it failed, it would not try connecting to next IP address as it does at the moment https://github.com/aio-libs/aiohttp/blob/8c25b44770e56ee5636d16d65687a732e1545c5a/aiohttp/connector.py#L1015-L1023
* `sock_connect` timeout that limits runtime of `loop.create_connection()` currently. https://github.com/aio-libs/aiohttp/blob/8c25b44770e56ee5636d16d65687a732e1545c5a/aiohttp/connector.py#L945-L946 The runtime would be significantly smaller because the method would use an already connected socket. Probably, we'd need to split the timeout into two separate ones.

**Comment by bdraco** [comment]
ESPHome has the same/similar issue https://github.com/esphome/aioesphomeapi/pull/233

We need a happy eyeballs implementation that supports passing in a list of resolved addresses that works for python 3.8 for aiohttp so we can solve https://github.com/aio-libs/aiohttp/issues/4451#issuecomment-786890416

Ideally we build a lib for that which could be used for both esphome and aiohttp so we don't have to reinvent the wheel as I'm sure other places need it as well.

The 3.8 support will be a bit of a pain though since we need use a conditional import with <https://pypi.org/project/async-stagger/> as `asyncio.staggered.staggered_race` is only available on newer python which makes the whole thing more complex and would make sense to make it in a new library

If I find the time to build something for esphome, I'll do it as a new library with a compatible license in case there is a chance we can reuse it here.

**Comment by bdraco** [comment]
I've got three projects I'm working on that need this so I think my holiday project is going to be to build a permissive licensed library that they can all use

**Comment by bdraco** [comment]
```python
        for hinfo in hosts:
            host = hinfo["host"]
            port = hinfo["port"]

            # Strip trailing dots, certificates contain FQDN without dots.
            # See https://github.com/aio-libs/aiohttp/issues/3636
            server_hostname = (
                (req.server_hostname or hinfo["hostname"]).rstrip(".")
                if sslcontext
                else None
            )

            try:
                transp, proto = await self._wrap_create_connection(
                    self._factory,
                    host,
                    port,
                    timeout=timeout,
                    ssl=sslcontext,
                    family=hinfo["family"],
                    proto=hinfo["proto"],
                    flags=hinfo["flags"],
                    server_hostname=server_hostname,
                    local_addr=self._local_addr,
                    req=req,
                    client_error=client_error,
                )
```

If we swap out `_wrap_create_connection` with something like
`self._create_happy_eyeballs_connection` and still do a outer loop with all the hosts but the inner loop pops them out of the happy eyeballs connect logic once we reject one via the `if req.is_ssl() and fingerprint:` branch it should behave mostly the same sans the timing.

Unfortunately most of `loop.create_connection` needs to be reimplemented because it expects to get unresolved names and we have resolved names

Worse it looks like we have to resolve local addrs as well since technically that works now

**Comment by bdraco** [comment]
I sliced up the stdlib create_connection into a new library https://github.com/bdraco/aiohappyeyeballs to allow connecting with Happy Eyeballs when you already have a list of addrinfo and not a DNS name.

**Comment by Dreamsorcerer** [comment]
Is there any interest in adding something in asyncio upstream to support it as well later on?

**Comment by bdraco** [comment]
I think thats a good idea to be able to land it there at some point as the code is almost 100% extracted from cpython except the utils and added typing+tests.  

The current asyncio `create_connection` code could be broken into two functions with the new `start_connection` as the inner function which returns the socket, but thats getting ahead of things since it probably needs to live in the wild for a while in case we need to adjust anything.
