### ISSUE TITLE
AioHTTP not working with external address (only working in localhost)

### ISSUE THREAD

**Issue by Th0rgal** [aio-libs/aiohttp#4470]
## Long story short

I was working on my really simple project polymath using https://github.com/Th0rgal/Polymath, everything worked fine in local. I can for example do:
curl "localhost:8080/debug"
and I get:
"It seems to be working..."

So I deployed it to my vps ...but ``curl "hestia.oraxen.com:8080/debug"`` where hestia.oraxen.com is the url of my vps isn't working. It is working with ``curl "localhost:8080/debug"`` from ssh though.

## Expected behaviour
I should get this message even if using the domain name: "It seems to be working..."

## Actual behaviour
``curl: (7) Failed to connect to hestia.oraxen.com port 8080: Connection timed out``

## Steps to reproduce

Deploy https://github.com/Th0rgal/Polymath
Try ``curl "your_adress:8080/debug"``

## Your environment

I'm using a VPS from oracle cloud with nixos installed. Here is my configuration: https://github.com/Th0rgal/vps-hestia-nixos

As you can see I allowed the port 8080 in my firewall (I also tried to disable it completely and I got the same result).

**Comment by asvetlov** [comment]
Sorry, I have no idea what's wrong with your configuration but the environment setup is not the project duty.

**Comment by Th0rgal** [comment]
> 
> 
> Sorry, I have no idea what's wrong with your configuration but the environment setup is not the project duty.

But as I said the problem doesn't seem to come from the environment because even if with a disabled firewall I get the same problem: aiohttp doesn't listen to external adress. Do I have to specify the hostname in order to be able to listen to it?

**Comment by asvetlov** [comment]
aiohttp has no special logic that is different when the server is executed on localhost or publicly available IP.
Sorry, I've never worked with VPS mentioned by you and don't know how to configure it properly; this task is out of aiohttp scope anyway.
I would say that aiohttp-based servers deployed world-wide by many projects, and they work perfectly fine.
That's why I think the problem is not on aiohttp side but something is misconfigured.
