### ISSUE TITLE
Mypy reports wrong type hints for BodyPartReader

### ISSUE THREAD

**Issue by otahontas** [aio-libs/aiohttp#4746]
🐞 **Describe the bug**

I was following [File Uploads -section in aiohttp docs](https://docs.aiohttp.org/en/stable/web_quickstart.html?highlight=multipart#file-uploads) to create a multipart request parser to work with multiple file forms in one request. However, when running the example snippet through mypy, I'm getting complains about non-existent attributes. To my understanding it seems like mypy doesn't recognise object returned from `field = await reader.next()` as BodyPartReader. 

💡 **To Reproduce**

1. Install latest aiohttp (3.6.2) and mypy (0.770) with python 3.7.7
2. Run multipart-reader example found from [File Uploads -section in aiohttp docs](https://docs.aiohttp.org/en/stable/web_quickstart.html?highlight=multipart#file-uploads) through mypy
3. Mypy returns bunch of errors (see traceback below)

💡 **Expected behavior**
- Mypy shouldn't report any errors

📋 **Logs/tracebacks**

```
metadata_backend/api/views.py:24: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"
metadata_backend/api/views.py:24: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"
metadata_backend/api/views.py:25: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "read"
metadata_backend/api/views.py:25: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "read"
metadata_backend/api/views.py:28: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"
metadata_backend/api/views.py:28: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"
metadata_backend/api/views.py:29: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "filename"
metadata_backend/api/views.py:29: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "filename"
metadata_backend/api/views.py:34: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "read_chunk"
metadata_backend/api/views.py:34: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "read_chunk"
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.7.7
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
Name: aiohttp
Version: 3.6.2
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: /home/otahontas/.cache/pyenv/versions/3.7.7/envs/metadata-submitter-37/lib/python3.7/site-packages
Requires: async-timeout, attrs, yarl, multidict, chardet
Required-by: metadata-backend, aiohttp-devtools
```
```console
$ python -m pip show multidict
...
Name: multidict
Version: 4.7.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/otahontas/.cache/pyenv/versions/3.7.7/envs/metadata-submitter-37/lib/python3.7/site-packages
Requires: 
Required-by: yarl, aiohttp
```
```console
$ python -m pip show yarl
...
Name: yarl
Version: 1.4.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/otahontas/.cache/pyenv/versions/3.7.7/envs/metadata-submitter-37/lib/python3.7/site-packages
Requires: multidict, idna
Required-by: aiohttp

```

**Comment by paulefoe** [comment]
Hey, otahontas! Thanks for submitting this. 

I've had a lot of fun finding out why is that happening. Here's what I found out.

The types inside the library are actually correct.

We can mainly see 2 types of errors here and this is why:
1. `metadata_backend/api/views.py:24: error: Item "None" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"` - this one is coming from the fact, that you should validate the input, which is said in the docs too.
For example, you expect to have 3 fields sent to you from the frontend, so you do `field = await reader.next()` 3 times for each field, but the frontend sent to you only 2 fields and as a result, you've got `None` in your last call to `reader.next()` 
2. `metadata_backend/api/views.py:24: error: Item "MultipartReader" of "Union[MultipartReader, BodyPartReader, None]" has no attribute "name"` with that one I spent quite a few hours, but here what it is. Aiohhtp can handle a Multipart Media Type[1]. What this means is that such a field will return a MultipartReader in which case you should again ask for the next file because you've sent the bunch of files in a single body, then from each of these files you could safely `read_chunk` or get some properties like a name. You can read more about working with multipart here [2]

To answering your expecting behavior, I guess, that example should be treated as a simplified variant of what would you write in a real app. Obviously you will have some validators for your forms, so that shouldn't be an issue, but writing a lot of checks for a simple example might be a little bit of an overhead, what do you think?


[1] https://tools.ietf.org/html/rfc2046#section-5.1
[2] https://docs.aiohttp.org/en/stable/multipart.html#aiohttp-multipart

**Comment by asvetlov** [comment]
The type hint were updated in aiohttp 3.7.

Please feel free to reopen the issue or create a new one if the problem still exists.
