### ISSUE TITLE
Not work with url with ':'

### ISSUE THREAD

**Issue by pnvasko** [aio-libs/aiohttp#480]
Hi, 

get trouble with use aiohttp:
http://www.homeaway.com/search/refined/world/region:1/Leisure+Activities:golf
don't give correct answer. urllib.request work correct

regards,
V

**Comment by popravich** [comment]
Hi @pnvasko,
Can you be more specific? How exactly aiohttp does not provide correct answer?
I've just tried and got `200 ok` with body about 30Kb.

**Comment by pnvasko** [comment]
Change target url. For sample ask - http://www.homeaway.com/search/refined/world/region:1/Leisure+Activities:golf, get content like this page  http://www.homeaway.com/search

**Comment by popravich** [comment]
ok, I see.
Actually the problem is with `+` it gets quoted into `%2B`

**Comment by pnvasko** [comment]
What can I do ?

понедельник, 31 августа 2015 г. пользователь Alexey Popravka написал:

**Comment by popravich** [comment]
@fafhrd91, @asvetlov guys!
The problem is here [aiohttp/client_reqrep.py:178](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/client_reqrep.py#L178)
I've 'blamed' that line to the very begining (https://github.com/KeepSafe/aiohttp/commit/f382b5ffc445e45a110734f5396728da7914aeb6)
and I could not see why `path` should be re-quoted.
The `urlsplit` returns path as is, so if it was already quoted it gets double-quoted.
And it also leads to re-quoting of `location` header in redirects.

I think we should remove this quoting of path and leave it up to end-users.
What do you think?

**Comment by asvetlov** [comment]
I think we should make trivial one-page app displaying `request.raw_path` then open the page in browser and play with different characters in path string.

Reference to standard is also good but I like to see what does Chrome and Firefox in case of  suspicious symbols

**Comment by asvetlov** [comment]
I've made a PR for the issue: #484

URL requoting is borrowed from requests library, I've checked it in Chrome and Firefox also.

**Comment by pnvasko** [comment]
Thank you!

2015-09-01 21:48 GMT+07:00 Andrew Svetlov notifications@github.com:
