### ISSUE TITLE
Add an option to provide a custom StreamWriter class to ClientSession

### ISSUE THREAD

**Issue by tarasko** [aio-libs/aiohttp#4845]
🐣 **Is your feature request related to a problem? Please describe.**
The current StreamWriter doesn't attempt to send body and header together within the same request. Instead it creates a task that is executed by EventLoop later and that creates a potentially unwanted delay in case when header and body are small enough to fit into the same IP packet. Currently body and header are always sent within 2 different IP packets

💡 **Describe the solution you'd like**
We can pass a StreamWriter factory into ClientRequest constructor thereby allowing user to implement a custom writer that could cache header and body and call transport.write only when write_eof is called. User would have full control on when data is actually being written into transport

❓ **Describe alternatives you've considered**
Adding an option to StreamWriter that will enable squashing of header and body if it makes sense. But this will be a very invasive change and significantly more work to address all possible cases. I don't feel it's a good idea tbh, it is not extendable either

**Comment by asvetlov** [comment]
1. No. I think that providing a custom very internal StreamWriter class is very bad idea.
2. Yes, the analysis is slightly incorrect. StreamWriter doesn't create a task. If the socket's internal write buffer has enough space the `await writer.write()` call doesn't switch the execution context but runs as the single non-blocking call.
3. Yes, two TCP packets are usually sent because aiohttp uses two calls: `await writer.write_headers()` and `await writer.write()`. A custom writer doesn't solve this issue because the fix requires `web.Response()` tuning (or even replacement).
