### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp.server'

### ISSUE THREAD

**Issue by sskaditya** [aio-libs/aiohttp#4847]
🐞 **Describe the bug**

I have just installed SSE 

The module is not found

`ModuleNotFoundError: No module named 'aiohttp.server'`

```python-traceback
  File "demo.py", line 2, in <module>
    import sse
  File "/home/pi/Documents/RFID_Production/src/lib/python3.7/site-packages/sse/__init__.py", line 2, in <module>
    from .handler import *  # noqa
  File "/home/pi/Documents/RFID_Production/src/lib/python3.7/site-packages/sse/handler.py", line 4, in <module>
    from .protocol import Response
  File "/home/pi/Documents/RFID_Production/src/lib/python3.7/site-packages/sse/protocol.py", line 1, in <module>
    import aiohttp.server
ModuleNotFoundError: No module named 'aiohttp.server'
```

💡 **To Reproduce**

💡 **Expected behavior**

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
...
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
...
```
```console
$ python -m pip show multidict
...
```
```console
$ python -m pip show yarl
...
```

📋 **Additional context**

**Comment by webknjaz** [comment]
Hello, I don't know what SSE is but it clearly imports aiohttp. There's no `aiohttp.server` module in the current version of aiohttp. Maybe it relies on some old version of aiohttp.

FWIW this question is not related to aiohttp but to some third-party library. You should report this on that library's tracker instead. This has nothing to do with aiohttp.

Also, next time you want to report an issue, file the questionary because w/o that info there's not enough details hinting how to help you anyway.
