### ISSUE TITLE
aiohttp does poorly in JSON-encoded response benchmark

### ISSUE THREAD

**Issue by ariddell** [aio-libs/aiohttp#530]
See https://klen.github.io/py-frameworks-bench/

Any suggestions as to why aiohttp does so badly in this benchmark?

![aiohttp](https://cloud.githubusercontent.com/assets/19950/10118233/bc9db63a-6441-11e5-86ca-9ec3b8daa3db.png)

**Comment by fafhrd91** [comment]
This benchmark shows reality, it is not good load for aiohttp. If you most time just encode json objects then aiohttp is not good choice.

**Comment by ariddell** [comment]
Is there any additional intuition you can offer? Falcon, for example, uses the standard library json routines for encoding and decoding.

**Comment by fafhrd91** [comment]
The reason is aiohttp is event-driven. Tornado has lower performance too. Falcon is slightly different it has c-based server implementation. But performance of framework in most cases does not matter, I added a lot of performance optimization in 0.15.3 and in some tests performance increased 2-3 times, but what is interesting I haven't see any performance difference in high load project.

So performance of server/framework in most cases does not matter. And if it does then you need different language other than python

**Comment by asvetlov** [comment]
Agree with @fafhrd91 in general.
Comparison of sync and async frameworks is hard and highly depends of test suite. You can see another article with totally different results: http://blog.gmludo.eu/2015/02/macro-benchmark-with-django-flask-and-asyncio.html
I did not measured those myself but believe both tests are wrong.

Also I don't trust the picture: it shows that muffin is faster than aiohttp.
The source of my doubt is: muffin is built on top of aiohttp.
I don't believe that a loft may be faster than basement.

**Comment by ludovic-gasc** [comment]
Hello guys,

About @asvetlov answer:

I'm agree with you, benchmarks depend a lot about your use cases.
Don't believe benchmarks on the Web, benchmark your use cases by yourself, because it's almost impossible to predict the future values when you change a parameter.
To me, I see benchmarks as a tool to know when I will need to have more servers and/or to validate that my daemon's architecture is enough efficient to handle the load required by the client.
I don't believe in the benchmarks absolute numbers on the Web, however, time to time, I discover a good tip in benchmark tests suite itself, like with [FrameworkBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks), where you have some interesting config files or tips to improve efficiency.

Moreover, it's possible to make mistakes, especially with a macro-benchmark where you have a lot parameters, from the hardware to your source code.
About the link that @asvetlov has posted from my blog, I've made a mistake. I've explained that in the next blog post: http://blog.gmludo.eu/2015/03/benchmark-python-web-production-stack.html
However, to be the most clear for new comers on my blog, I've added a warning at the beginning of the first article: http://blog.gmludo.eu/2015/02/macro-benchmark-with-django-flask-and-asyncio.html

For muffin vs aiohttp, I recognize that theses numbers are very counterintuitive.
May @klen should add muffin in FrameworkBenchmarks tests suite to confirm theses counterintuitive results.

About @fafhrd91 answer:

Because IT is a scientific field like others, a sure thing in the past should become false with the new discoveries ;-)

Concretely, yes, for now, aiohttp is less efficient for small JSON payloads and no I/O interactions in the backend.
Even if it isn't very frequent to have this use case (at least to me), I've some differents numbers for the next FrameworkBenchmarks round 11 (preview results, not final):
https://www.techempower.com/benchmarks/previews/round11/#section=data-r11&hw=peak&test=json&l=a598g

As you can see, with aiohttp, few perfs like with tornado.
However, when I use AsyncIO low API (callbacks) directly to answer (API-Hour+asyncio) instead of aiohttp, I've a lot of performances. I know, I didn't implement all HTTP protocol like in aiohttp, however, some increases should be possible.

Moreover, when I use AsyncIO high API (coroutines) to answer, now, aiohttp is really more efficient:
https://www.techempower.com/benchmarks/previews/round11/#section=data-r11&hw=peak&test=db&l=a598g

Yes, theses results seem to be counter-intuitive, however, I've observed the same on my benchmarks setup.

My feeling is that the "issue" should be more coroutines vs callbacks architecture efficiency than something else, but no concrete data to validate that. If you have any clues, I'm really interested in.

Moreover, for now, AsyncIO and aiohttp are mostly in Python.
If one day, we have more C parts like Falcon, maybe the results should change a lot.

However, on big projects, as explained by @fafhrd91, it's often your own business logic that consumes resources than the framework itself.

About to change programming language, I'm not sure the cost to change the toolbox of a dev team + habits of a sysadmin team + difficulty to find new people should justify that, except if you want to take the opportunity to change the balance in a dev team.
Human costs >>>> Servers costs ;-)

To me, more I dig in the Python performances field, more I think that it's the architecture in applications, the size of community and the economic stakes that the language itself that should change the speed: Look Javascript, because Google has made V8, now JS and VMs in JS in general are very efficient.

Maybe if people who have implemented V8, now if they implements a VM for Python, maybe things should be different.

For now, I've always found a solution to bypass efficiency issues I had with Python: I believe it costs less to me than to change my main programming language.
If one day it won't be the case anymore, I'll change my toolbox: Programming languages are only tools.
Except geeks, who really cares the programming language you use ?

**Comment by ariddell** [comment]
Ok, so this is becoming clearer. For aiohttp to shine these/similar benchmarks one should at least include a benchmark where websockets are used (in which case falcon wouldn't even appear in the rankings, https://github.com/falconry/falcon/issues/321).

Thanks for the education here! I'm definitely in agreement with @GMLudo that ease of use counts for a lot. It was, to be honest, the magnitude of the difference in the benchmark that grabbed my attention (falcon: 23k req/seq, aiohttp: 4k).

**Comment by ludovic-gasc** [comment]
About WebSockets benchmark, it's planned in FrameworkBenchmarks. 

About Falcon itself, I've discussed a little bit with his creator during PyCON US. It may possible to reuse some parts for aiohttp, but finally, I've never find time to dig in this way.

Be my guest if you're interested in to contribute in this way.

**Comment by ariddell** [comment]
I'd be willing to help out with websocket performance work if I understood what the issues were (or, really, if there _are_ any real issues). My main use case does involve a lot of pretty simple json encoding/decoding over a websocket. If writing some C code could help a lot, I'd be willing to take a stab at it.

**Comment by klen** [comment]
@asvetlov @GMLudo About Muffin's results above. I used default frameworks' examples to pass the benchmark. But Muffin installs and uses ujson (instead standart json module) by default. It's not about speedup some results (https://github.com/klen/py-frameworks-bench/blob/develop/frameworks/muffin/app.py#L39), but default behaviour. That the reason for the difference.

**Comment by ludovic-gasc** [comment]
@ariddell about Request/Response pattern with HTTP, you have a lot of benchmarks on the Web.
About WebSockets, I wouldn't transpose results from classical HTTP benchmarks, because you don't have the same behaviour at application level.
Sorry to repeat, however, benchmark your use case and profile, to be sure to understand where you have efficiency issues.
I recommend you to read this book: [High Performance Python](http://shop.oreilly.com/product/0636920028963.do)
At least to me, I've understood better how to measure and improve correctly my source code.

**Comment by ariddell** [comment]
Thanks! You're absolutely right about benchmarking and profiling my own use case.
