### ISSUE TITLE
How to make response picklable

### ISSUE THREAD

**Issue by howie6879** [aio-libs/aiohttp#5378]
🐞 **Describe the bug**

When I need to persist the response, display:

```shell
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
```

💡 **To Reproduce**

code sample:

```python
import asyncio
import pickle

import aiohttp


async def main():

    async with aiohttp.ClientSession() as session:
        async with session.get("http://python.org") as response:

            print("Status:", response.status)
            print("Content-type:", response.headers["content-type"])

            html = await response.text()
            print("Body:", html[:15], "...")
            pickle.dumps(response)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())

```

I wrote an asynchronous crawler framework based on aiohttp. When I implemented a cache plug-in, I found that the response class could not be persisted. Do you have any suggestions for this problem?

💡 **Expected behavior**

Hope that the response class can be persisted locally

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)
Status: 200
Content-type: text/html; charset=utf-8
Body: <!doctype html> ...
Traceback (most recent call last):
  File "/Users/howie6879/Documents/Programming/Python/git/ruia-cache/examples/issue.py", line 26, in <module>
    loop.run_until_complete(main())
  File "/Users/howie6879/anaconda3/envs/python36/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/Users/howie6879/Documents/Programming/Python/git/ruia-cache/examples/issue.py", line 22, in main
    pickle.dumps(response)
TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
```

📋 **Your version of the Python**

```console
$ python --version
Python 3.6.8 :: Anaconda, Inc.
```

📋 **Your version of the aiohttp/yarl/multidict distributions**

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.7.3
```
```console
$ python -m pip show multidict
Name: multidict
Version: 4.7.6
```
```console
$ python -m pip show yarl
Name: yarl
Version: 1.6.3
```

📋 **Additional context**

**Comment by webknjaz** [comment]
> ```python-traceback
> TypeError: can't pickle multidict._multidict.CIMultiDictProxy objects
> ```

It's not pickleable by design: https://github.com/aio-libs/multidict/issues/340.



> I wrote an asynchronous crawler framework based on aiohttp. When I implemented a cache plug-in, I found that the response class could not be persisted. Do you have any suggestions for this problem?

There's no point/possibility to pickle the response object. It holds references to ephemeral things like a response stream reader, HTTP session / TCP connection. The HTTP response body is not stored there either, the end-user must call the reader coroutine method but themself. Even if it was possible to pickle this object, it'd be useless because it'd point to non-existent TCP streams outside of the async context manager.

You have to read all the data you need while it's available and cache that instead. Note that there's a reason behind not reading the body automatically: it could be huge and eat up all memory so you'll need to take that into account in your app.
