### ISSUE TITLE
Client: Range/Partial content not working

### ISSUE THREAD

**Issue by MerlijnWajer** [aio-libs/aiohttp#5513]
🐞 **Describe the bug**

I'm trying to specify the "Range:" header to fetch partial content from a server. This works with curl, but I cannot get it to work with aiohttp - the full document is returned, and the status code is 200, not 206. Perhaps the headers aren't passed properly to the remote server, since the status code is 200.

💡 **To Reproduce**

Check that curl works:

```
curl -v https://ia801507.us.archive.org/28/items/sim_english-illustrated-magazine_1884-12_2_15/sim_english-illustrated-magazine_1884-12_2_15_hocr.html  -H 'Range: bytes=406259-541176'
```

Python code:

```
import aiohttp
import asyncio

async def main():
    url = 'https://ia801507.us.archive.org/28/items/sim_english-illustrated-magazine_1884-12_2_15/sim_english-illustrated-magazine_1884-12_2_15_hocr.html'
    headers={'Range': 'bytes=406259-541176'}

    async with aiohttp.ClientSession(headers=headers) as session:
        async with session.get(url) as response:

            print("Status:", response.status)
            print("Content-type:", response.headers['content-type'])

            html = await response.text()
            print('Body length:', len(html))

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

Results in:

```
$ python3 /tmp/aio-example.py
Status: 200
Content-type: text/html; charset=utf-8
Body length: 12419537
```

💡 **Expected behavior**

The response should return a 206 as status and only the partial content is returned.

📋 **Logs/tracebacks**

```python-traceback (paste your traceback in the next line)

```

📋 **Your version of the Python**

```console
$ python --version
Python 3.6.12

```

📋 **Your version of the aiohttp/yarl/multidict distributions**

aiohttp `3.7.3`

📋 **Additional context**

Using Linux, on Gentoo. But the same problem exists in a alpine docker container.

**Comment by JustinTArthur** [comment]
The problem you're running into is that both the client and server are trying to be overly helpful to you :)

- aiohttp thinks you'd probably want compression if the server is able to do it
- archive.org's nginx wants to give you the compression aiohttp asks for. It also knows that you wouldn't be able to decode a mid-section of a gzip stream and knows you probably wouldn't have been able to accurately guess where in the stream to take bytes from. It has to decide between giving you a byte range 206 response or a complete gzipped 200 response. It chooses the latter ([related nginx forum thread](https://forum.nginx.org/read.php?2,209738,210053#msg-210053)).

The quick fix is to override aiohttp's automated ask for compression, e.g.:
```python
session.get(url, headers=headers, skip_auto_headers=(aiohttp.hdrs.ACCEPT_ENCODING,))
```
In an ideal world, you can go a step further and still prefer some compression, but at the transport layer instead of in the content you're slicing:
```python
headers={'Range': 'bytes=406259-541176', 'TE': 'gzip, deflate'}   # This WON'T work with your setup
```
however, nginx won't compress given that prompt, and aiohttp won't auto-decompress even if it did. Not many web components speak http 1.1's `Transfer-Encoding` language outside of basic chunking.

**Comment by JustinTArthur** [comment]
You would run into the same problem with curl, but only if you pass curl the `--compress` option. With both curl and aiohttp, you have to be ready for a server that simply doesn't send you a partial byte range back.

I would recommend the `skip_auto_headers` quick fix for your case. You could leave this open if you want to consider it a feature request for native byte range support in the API, e.g. something like `session.get(start_byte=406_259, end_byte=541_176)`. If so, consider adjusting the ticket name or opening a new one.

**Comment by MerlijnWajer** [comment]
Thanks for the solution, I think we can close the ticket.
