### ISSUE TITLE
Rename `path` param to `url` in aiohttp-pytest plugin

### ISSUE THREAD

**Issue by inyutin** [aio-libs/aiohttp#5519]
🐣 **Is your feature request related to a problem? Please describe.**
Let's imagine I use a function that looks like this:
```python
def function(client: ClientSession, url: StrOrURL) -> web.Response:
    return await self.client.get(url=url)
```
Of course, I want to test this function. So, I write code like this:
```python
async def ping_handler(self, _: web.Request) -> web.Response:
    return web.Response(text='Ok!', status=200)

async def test_function(aiohttp_client, loop)
    app = web.Application() # of  course, in real code I add some routes
    app.router.add_get('/ping', self.ping_handler)
    client = await aiohttp_client(app)
    await function(client, '/ping')
```    

However, this code fails, because ```aiohttp_client(app).get``` have another signature, it doesn't have ```url``` param, it have ```path```.

pytest aiohttp client get:
https://github.com/aio-libs/aiohttp/blob/25dfe50e5203dd77778a668fd005250dceaccf05/aiohttp/test_utils.py#L322

real aiohttp client get:
https://github.com/aio-libs/aiohttp/blob/7c2b50d1f1c8067d9a2fc230b3ef401cfb2cf6d2/aiohttp/client.py#L875

It's just a simple example without any particular meaning. I also can't change the way I use ```get``` method, I can't simply remove ```url=url```. Or I use pytest aiohttp client wrong?

💡 **Describe the solution you'd like**
So, what I suppose is to change ```path```  to ```url``` to make signatures same. What do you think?

**Comment by Dreamsorcerer** [comment]
I think these classes are unrelated (e.g. Your code would give you a type error in mypy, because you passed `TestClient` into a function expecting `ClientSession`).

`TestClient` is used in tests to make requests to the local server, see https://docs.aiohttp.org/en/stable/testing.html#the-test-client-and-servers

You need to pass a `ClientSession` object or a mock for testing purposes. Passing a mock, you could then test your function with something like: `mock.get.assert_awaited_once_with(url='/ping')`

**Comment by Dreamsorcerer** [comment]
Or without needing to pass the client object at all, you could try mocking requests with https://github.com/pnuckowski/aioresponses or something similar.
