### ISSUE TITLE
notify method support

### ISSUE THREAD

**Issue by andrew-ld** [aio-libs/aiohttp#5567]
🐣 **Is your feature request related to a problem?** yes
I'm implementing error handling in my iot devices (upnp device) that send status to a web server via the NOTIFY method

💡 **Describe the solution you'd like**
aiohttp should correctly handle the NOTIFY method

📋 **Additional context**

I would like to embed this web server directly in my aiohttp instance in a clean way:

https://github.com/StevenLooman/async_upnp_client/blob/ef5735a3b051cbaad5582d9d98fb1f65e0e8eded/async_upnp_client/aiohttp.py#L184

I cannot do it because I cannot create a route that manages a request with NOTIFY method

**UPNP documentation:**

https://openconnectivity.org/upnp-specs/UPnP-arch-DeviceArchitecture-v2.0-20200417.pdf

**example request:**

![Screenshot_20210326_235451](https://user-images.githubusercontent.com/43882924/112700511-9f0f1c80-8e8e-11eb-94ca-91847dad013a.png)

**Comment by Dreamsorcerer** [comment]
Umm, why not?

```python
from aiohttp import web

async def handle(request):
    return web.Response(text="NOTIFIED")

app = web.Application()
app.router.add_route("NOTIFY", "/", handle)

if __name__ == '__main__':
    web.run_app(app)
```

```console
> curl -X NOTIFY http://0.0.0.0:8080
NOTIFIED
```

Seems to be working to me.

**Comment by andrew-ld** [comment]
_in a clean way_

I'd like it if it would be typed like the rest of the methods

**Comment by Dreamsorcerer** [comment]
I'm not following, can you provide some code demonstrating what you want?

**Comment by andrew-ld** [comment]
NOTIFY is a post method

https://github.com/aio-libs/aiohttp/blob/742a8b6d09b2623670ddede838c913d2a8a4d89e/aiohttp/client_reqrep.py#L164

NOTIFY should be added

https://github.com/aio-libs/aiohttp/blob/742a8b6d09b2623670ddede838c913d2a8a4d89e/aiohttp/hdrs.py#L21

NOTIFY should be added

https://github.com/aio-libs/aiohttp/blob/742a8b6d09b2623670ddede838c913d2a8a4d89e/aiohttp/web_routedef.py#L116

NOTIFY should be added

https://github.com/aio-libs/aiohttp/blob/742a8b6d09b2623670ddede838c913d2a8a4d89e/aiohttp/web_routedef.py#L156

I honestly don't know how many places you would need to add it for full support

**Comment by Dreamsorcerer** [comment]
Right, I see, though I'm not sure if it's worth aiohttp trying to add constants for every method that any standard or application decides to invent. That seems like it would be difficult to maintain. I assume the existing set of methods are the ones actually defined in the HTTP standard:
https://tools.ietf.org/html/rfc7231#section-4

I suspect that supporting others with dedicated methods and constants is probably out of scope.

**Comment by webknjaz** [comment]
Sam is right. `NOTIFY` is not a standard HTTP method defined in RFC 7231 and aiohttp is an HTTP web-framework. The main focus is to support building common HTTP client and server apps. As such, adding a dedicated `NOTIFY` method is simply out of scope for us.

Making an exception for this FR is not an option because it'd open up a can of worms and be a dangerous precedent. Other people will start requesting adding every possible method name from every possible standard or even not having a standard but present in some specific person's app.
We need to think about covering the common cases, not every possible corner case an average user will never need. If one person in the world needs something, it doesn't need to be in the codebase that everybody else would receive. We need to consider how this would affect other users too. Plus every change to the framework is a maintenance burden that the maintainers end up struggling with, not the contributors.
