### ISSUE TITLE
Posting bytes without sending as a file

### ISSUE THREAD

**Issue by penn5** [aio-libs/aiohttp#5605]
🐣 **Is your feature request related to a problem? Please describe.**

I want to send raw bytes to a server without sending it as a file or encoding as unicode

💡 **Describe the solution you'd like**

A flag to be added to FormData.add_field to disable making bytes into a file automatically.

❓ **Describe alternatives you've considered**

Urlencode it by hand

📋 **Additional context**

No?

**Comment by paulefoe** [comment]
From the documentation:

If you want to send data that is not form-encoded you can do it by passing a bytes instead of a dict. This data will be posted directly and content-type set to ‘application/octet-stream’ by default:
```
async with session.post(url, data=b'\x00Binary-data\x00') as resp:
```

Is this what you are looking for?
If not, can you please describe in a more details what is your use case?

**Comment by penn5** [comment]
> From the documentation:
> 
> If you want to send data that is not form-encoded you can do it by passing a bytes instead of a dict. This data will be posted directly and content-type set to ‘application/octet-stream’ by default:
> 
> ```
> async with session.post(url, data=b'\x00Binary-data\x00') as resp:
> ```
> 
> Is this what you are looking for?
> If not, can you please describe in a more details what is your use case?

I wanted to post data which is stored as bytes. But it worked when I just set encoding as latin-1, since it's the same one used in http.
