### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by meisimo** [aio-libs/aiohttp#5631]
I have noted that the discussion about HTTP 2 support has years closed, but I have found that the trend of HTTP 2 has increased, already is over the 50% of the internet. [This is my reference :D](https://w3techs.com/technologies/details/ce-http2#:~:text=HTTP%2F2%20is%20the%20second,of%20the%20HTTP%20network%20protocol.&text=HTTP%2F2%20is%20now%20used,from%2042.6%25%20one%20year%20ago.)

Maybe its not the purpose of this lib, but I love to use it for web scrapping and this feature would be great! :D

Relatef issues
https://github.com/aio-libs/aiohttp/issues/320
https://github.com/aio-libs/aiohttp/issues/863

**Comment by Dreamsorcerer** [comment]
Seems you've already found the existing discussion around this.

Basically, we'd all like to have HTTP/2 support available, but nobody is working on it. Opening an issue requesting it again is, unfortunately, not going to make it happen. Until someone volunteers to implement it, I'm afraid we're stuck without.

I'm not sure how much benefit it would provide for your web scraping though. Almost all sites still support HTTP/1.1, and my impression of the performance benefits is that it helps speed up getting extra files that are needed by a browser for the web page. Files that you probably won't need if you are web scraping.

**Comment by Granitosaurus** [comment]
@Dreamsorcerer sorry to revive a closed issue but to asnwer your question:

> I'm not sure how much benefit it would provide for your web scraping though

It's very easy to identify and block web scrapers when most of the real traffic is HTTP2.

**Comment by webknjaz** [comment]
Just to reiterate: this is an open source project happy to accept contributions. A PR for this feature will probably be submitted by someone who *really-really* needs it. Since nobody attempted it so far, it doesn't look like an ultimate priority for the end-users 🤷‍♂️
Prove me wrong :)

**Comment by lilydjwg** [comment]
I understand that this is an open source project, but I don't understand why you close the issue (and lock the other). This makes it harder to find if this project has support it or not (or if a patch will be accepted or not). 

I saw this new issue closed and thought it had been implemented finally. It turned out not.

**Comment by jameshilliard** [comment]
Not sure if anyone has looked into this in detail yet but [apparently twisted was able to add http2 support](https://github.com/twisted/twisted/blob/twisted-22.10.0/src/twisted/web/_http2.py) via the [h2 library](https://github.com/python-hyper/h2), I wonder if a similar approach may be workable for aiohttp.

**Comment by webknjaz** [comment]
@jameshilliard we have two implementations for things that tend to be slow — one in pure Python and the other in Cython (using the llhttp bindings in case of the HTTP parser).

I'm aware that h11 and h2 exist, but somebody would still have to implement the C-extension version with a similar functionality. We'd need feature parity for this to be acceptable.

**Comment by jameshilliard** [comment]
> I'm aware that h11 and h2 exist, but somebody would still have to implement the C-extension version with a similar functionality. We'd need feature parity for this to be acceptable.

That may not be too difficult as it appears to have been supported by [h2](https://github.com/python-hyper/h2)'s header parser in the past, [h2](https://github.com/python-hyper/h2) itself does not appear to actually do parsing itself, it seems to use the [hpack](https://github.com/python-hyper/hpack) backend for header parsing which could have an optimized backend swapped in.

For [hpack](https://github.com/python-hyper/hpack) it even appears that using the optimized nghttp2 c module [was supported at some point](https://github.com/python-hyper/hpack/blob/v2.3.0/hpack/hpack_compat.py), so using the nghttp2 based c module may be one approach for getting optimized us http2 hpack header parsing working with [h2](https://github.com/python-hyper/h2).

In terms of how h2 would be wired up it looks to me like we'd potentially want to hook callsites like [`data_received`](https://github.com/aio-libs/aiohttp/blob/71ae610e4d8350f1f1f121164b75ce3ad78d7902/aiohttp/web_protocol.py#L352-L389) similar to the twisted [`dataReceived`](https://github.com/twisted/twisted/blob/cf97936d3a09e8e596db80dff8c69642d75413e7/src/twisted/web/http.py#L3102-L3151) hook, does that seem like it might be viable?

Would we need to pull [h2](https://github.com/python-hyper/h2) into the aiohttp codebase so that it can customized or would it make sense to try and use it as is potentially?

**Comment by Dreamsorcerer** [comment]
> @jameshilliard we have two implementations for things that tend to be slow — one in pure Python and the other in Cython (using the llhttp bindings in case of the HTTP parser).

Just to put another option out there that's worth considering. mypyc can compile typed code to C extensions automatically, so that could allow us to have only 1 version of code to maintain.

**Comment by jameshilliard** [comment]
> mypyc can compile typed code to C extensions automatically, so that could allow us to have only 1 version of code to maintain.

Autotranslated code like that tends to not be as good performance wise as native c libraries. Also [alpha quality](https://github.com/mypyc/mypyc#development-status) libraries/tools aren't probably a great option here.

**Comment by Dreamsorcerer** [comment]
Well, we wouldn't know the performance unless we tested it. I don't mind which way we go, but might save a lot of time using mypyc, and make it easier for contributors who wouldn't need to learn Cython to work on these parts of the code.

That alpha warning is 2 years out of date. The project seems to be in a stable position these days. _If_ mypyc produces an output for your code, it should be reliable. The main issue currently is that there are still several features unsupported (e.g. async generators won't compile currently), but those missing features will probably not be used in the code we're talking about.

**Comment by FeldrinH** [comment]
Would it be possible to reopen this issue to make it clear for those interested that HTTP2 support is currently not implemented? I think it will be easier to find interested contributors if there is a clear open issue requesting HTTP2 support.

**Comment by sfc-gh-fpawlowski** [comment]
This would be very important to have. Are there any plans for it in the near future?

**Comment by cynthia2006** [comment]
@sfc-gh-fpawlowski Maybe no. And, ideally you'd want HTTP/3 at this age, because QUIC is standardised in 2021, and — even if not many — websites have begun to use HTTP/3 in practice. Much of the Python infrastructure (e.g. requests, urllib, urllib3, and this) remains tied HTTP/1.1, while others (e.g. libcurl, reqwests) have support for HTTP/3 for quite a while.

**Comment by Dreamsorcerer** [comment]
This is being tracked in #5999, but is still waiting for a volunteer or substantial sponsorship to fund development.

**Comment by asadnuts** [comment]
question is, will they stuck at HTTP/1 forever?

**Comment by cynthia2006** [comment]
@asadofc Unfortuntely, yes. HTTP/1.1 isn't necessarily bad, but it's considered outdated in a world where almost 40% websites use HTTP/3, which use QUIC for noticeable benefits.

**Comment by ac130kz** [comment]
@cynthia2006

> Unfortuntely, yes. HTTP/1.1 isn't necessarily bad

Sadly, it is bad. HTTP/1.1 is by design prone to desync attacks.

Source: ["HTTP/1.1 must die: the desync endgame"](https://portswigger.net/research/http1-must-die) by James Kettle

**Comment by Dreamsorcerer** [comment]
Unless you are proposing to implement this feature, or fund development of it, please stop spamming these issues.
