### ISSUE TITLE
Providing a custom Request class in aiohttp.web

### ISSUE THREAD

**Issue by dgilland** [aio-libs/aiohttp#624]
Currently, it's not easy to have `RequestHandler` use a custom `Request` class: https://github.com/KeepSafe/aiohttp/blob/0.18/aiohttp/web.py#L65

Having something like the following implemented could allow an easier way to override the default class used for the request object:

``` python
class MyRequest(Request):
    pass

class MyRequestHandler(RequestHandler):
    request_class = MyRequest

    @asyncio.coroutine
    def handle_request(self, message, payload):
        # ...snip...
        request = self.request_class(
            app, message, payload,
            self.transport, self.reader, self.writer,
            secure_proxy_ssl_header=self._secure_proxy_ssl_header)
        # ...snip...

# Quick and dirty example of using custom handler
class MyRequestHandlerFactory(RequestHandlerFactory):
    def __init__(self, *args, **kargs):
        kargs['handler'] = MyRequestHandler
        super().__init__(*args, **kargs)

app = web.Application(handler_factory=MyRequestHandlerFactory)
```

There are probably better ways to implement a custom `Request` class, but any thoughts on the concept itself? Is this something that would be considered?

**Comment by fafhrd91** [comment]
What is the use case for custom request class?

**Comment by dgilland** [comment]
My immediate use case is to override the default `loader` value in [Request.json](https://github.com/KeepSafe/aiohttp/blob/0.18/aiohttp/web_reqrep.py#L326).

**Comment by asvetlov** [comment]
Using custom request classes is just wrong.
Constructor parameters are not documented and may be changed in the moment without any deprecation period in backward-incompatible way.
If you need another loader -- do it explicitly:

```
@asyncio.coroutine
def load_json(request):
    return (yield from request.json(loader=custom_loader))
```

**Comment by alvassin** [comment]
@asvetlov, what about body validation? What is the best way to implement middleware for validating request body, for example RAML (i use it in several projects).

It is necessary to check if resource url and http method is present in RAML and request body. Request body can be read only once - it's a stream. 

My idea is to:
- implement middleware that would validate resource url + http method against RAML
- decorate method `Request.json()` with validation method, that would check Request body stream against RAML and raise exception in case it is invalid or provide custom method.

I do not want users to write extra code for each handler for call against RAML validation. I would like to have DRY setup for such validation in one place.

Another idea - to read body stream from request and store it in request['body'] key seems to be far from ideal. It would be not flexible enough. 

Third idea - to monkey-patch request object in middleware, to add validation decorator for its `json` method.

What do you think?

**Comment by asvetlov** [comment]
I still think the request customization leads to a mess.
Request object is a complex contract, customized or monkeypatched version can break existing behavior easy.

Keep calm and do a validation explicitly -- it is better from error handling perspective anyway

**Comment by avanov** [comment]
@asvetlov custom request factories work pretty well in Pyramid and don't lead to a mess. They are just required to follow the specified interface (and it could be checked during app init phase), and the rest is handled by the framework router.
* https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/hooks.html#changing-the-request-factory
* https://docs.pylonsproject.org/projects/pyramid/en/latest/api/config.html#pyramid.config.Configurator.set_request_factory
* https://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html?highlight=IRequestFactory#pyramid.interfaces.IRequestFactory

**Comment by asvetlov** [comment]
I still don't see the use case

**Comment by avanov** [comment]
One of the use cases I have in mind - custom API-related attributes, such as API version number, customer token identifier etc. By the time a request object is created, this information is already available through request headers, and I can initialise my request object with all these attributes set, instead of relying on a custom middleware setting these values into a dict-like collection of the framework-default request object. Then, I can use my request object class in type hints to provide IDEs and MyPy with extra information about those custom attributes, which helps in static type checking and refactoring (for instance - "I'd like to see all places in our code where we access Customer Token").

**Comment by asvetlov** [comment]
I see a scaling problem here: only one library can override request factory to provide custom methods/properties. It means that another code cannot use own overrides.

Better to provide top-level functions for custom properties, e.g.
```
def custom_property(request):
     return parse(request.headers.get('X-Custom-Token')

async def handler(request: web.Request) -> TokenType:
     token = custom_property(request)
```
Request storage could be used for caching values if needed.

Moreover, the idea of providing type hints by custom request factory doesn't work: the signature of web-handler is `async def handler(web.Request) -> web.StreamResponse: ...`, using custom factories require downcasting `web.Request` type.

**Comment by avanov** [comment]
> I see a scaling problem here: only one library can override request factory to provide custom methods/properties. It means that another code cannot use own overrides.

In frameworks that support custom factories, there's the following strategy in place:

* Only framework users are allowed to define what factory is used across their entire application.
* Libraries are not allowed to impose new request factories incompatible with the framework-defined protocol, they just suggest using their factory on top of it, or consume whatever request is actually in place. This works, because there's a strictly defined interface (protocol) of what a request object is, regardless of the actual factory.

> Moreover, the idea of providing type hints by custom request factory doesn't work: the signature of web-handler is `async def handler(web.Request) -> web.StreamResponse: ...` using custom factories require downcasting `web.Request` type.

Not sure what you mean by downcasting here. Do you think that structural subtyping is not good enough in this case? I mean [this particular approach](https://mypy.readthedocs.io/en/latest/protocols.html#simple-user-defined-protocols), where an author of a framework relies on a protocol, rather than a particular implementation, when defining public API.

**Comment by asvetlov** [comment]
Heh, you want to sell me a complex magic while the simple and obvious solution for your use-case already exists.
