### ISSUE TITLE
access log format is invalid when using gunicorn worker

### ISSUE THREAD

**Issue by sontek** [aio-libs/aiohttp#705]
It seems you have to pass in `--access-logformat='%a %l %u %t "%r" %s %b "%{Referrer}i" "%{User-Agent}i"'` to gunicorn for logging to work, they default format from gunicorn is `"%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"` which doesn't work with aiohttp

**Comment by zeroaltitude** [comment]
I have found this problem too, just today.  Thank you for the workaround.

**Comment by FrederikNJS** [comment]
Just ran into this issue... Took me a couple of hours to find this answer. Thanks for the workaround, I was starting to get grey hairs.

**Comment by anthonylau** [comment]
https://github.com/benoitc/gunicorn/issues/1300
might be related, can't get metrics on statsd

**Comment by miedzinski** [comment]
This is still an issue.

**Comment by tumb1er** [comment]
Gunicorn config defaults are invalid for `aiohttp.helpers.AccessLogger.log_format`. To fix this, you need to change at least `%a` behavior, and may be other format arguments that intersect between http://docs.gunicorn.org/en/stable/settings.html#access-log-format and http://aiohttp.readthedocs.io/en/stable/logging.html#format-specification.
This at least backward-incompatible change, but it'll be very nice to fix it finally.

Other option is to pass access logger class to  `RequestHandler` arguments from gunicorn worker, but it's too complicated.

**Comment by asvetlov** [comment]
We can make a workaround.
1. Replace _default gunicorn_ logger format with _default aiohttp_ one on worker initialization.
Follow step may be:
2. Add a checker for _gunicorn logging style_ and raise an explicit error on worker initialization
It can be just regexp for `%(name)s` parts in logging spec.

We can also add a support for _gunicorn style_ but it requires much more work and the solution is very complicated from my perspective.

@f0t0n maybe you have an interest in fixing the issue?

**Comment by f0t0n** [comment]
@asvetlov Gunicorn's `Arbiter` reads the gunicorn config, then [creates a logger](https://github.com/benoitc/gunicorn/blob/13d193736d0097245237ec235de4248a765b61ba/gunicorn/arbiter.py#L95) and passes it to [worker's constructor](https://github.com/benoitc/gunicorn/blob/13d193736d0097245237ec235de4248a765b61ba/gunicorn/arbiter.py#L542).

> 1. Replace default gunicorn logger format with default aiohttp one on worker initialization.

In this way if we call `self.log.setFormatter()` inside worker's constructor with formatter that uses default aiohttp's format string `aiohttp.helpers.LOG_FORMAT` we're not able to read one from gunicorn config since it's too late to override.

> 1. Add a checker for gunicorn logging style and raise an explicit error on worker initialization
>    It can be just regexp for %(name)s parts in logging spec.

Also I don't see a correct way to retrieve a format string from logger  like `self.log.handlers[0].formatter._fmt` since this string is a [protected member](https://hg.python.org/cpython/file/5c4ca109af1c/Lib/logging/__init__.py#l462) of `logging.Formatter` class.

**Comment by tumb1er** [comment]
access_logformat from gunicorn config is passed from [GunicornWebWorker](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/worker.py#L51) to ServerHttpProtocol, which [constructs](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/server.py#L130) AccessLogger "wrapper" with gunicorn (invalid) default format instead of aiohttp's one.

For me, access logs work with:

``` sh
gunicorn --worker-class=aiohttp.worker.GunicornWebWorker 
  --access-logformat="..." 
  --log-config=logging.conf
```

logging.conf part:

``` ini
[logger_gunicorn.access]
level=INFO
handlers=access_file
propagate=0
qualname=gunicorn.access

[handler_access_file]
class=logging.handlers.TimedRotatingFileHandler
formatter=access
args=('/data/logs/access.log', 'midnight')

[formatter_access]
format=%(message)s # That's what glogger receives from AccessLogger wrapper
class=logging.Formatter
```

**Comment by f0t0n** [comment]
Ok, I'll try to work with `self.cfg.access_log_format`.
