### ISSUE TITLE
Does ClientResponse.release() method make sense?

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#739]
Today I've told with @tailhook 

He said `.release()` should be an alias to `.close()`: accurate user have read the whole request, not _status code_ / _headers_ only. If one don't want to do it the response should be closed with socket disconnection.

As worst case he mentioned the scenario when user process headers only for streaming response without coping with the body.

The standard code for client API is:

```
async with session.get(url) as resp:
    print(resp.status, resp.headers)
    # don't close response
```

Streaming server may send data forever, `.release()` will never end.
It's astonishing at least.

As side effect we can implement `with statement` for response, not only `async with`.
I think we should implement both (as well as for ClientSession) but document only one method.

Honestly I don't know what's better suits to aiohttp: from one hand it should encourage `async with` support but from other just `with` is enough.

Say again I would support both `with` and `async with`, the question is what to promote in the docs?

Thoughts?

**Comment by tailhook** [comment]
While I think that promoting `async with` is probably good enough. Using direct `with` better communicates the idea that "okay we close problematic connection now, no waiting here".

Another issue is that, if the user sent a request, and _successfully_ exits from the `with` without either reading the body or closing the connection explicitly, I believe the warning should be issued. Since if you just want to inspect headers, please, send the `HEAD` request. Otherwise, partial reception of body is a bug in 90% use cases. And you can always receive the full body or close the connection explicitly if that's what you want.

While the last paragraph is definitely good in the ideal world, in the real world there are `200 Ok` responses with some tiny content which are used instead of `204 No Content` responses. I.e. you don't need to read the body. It's tempting to treat small bodies (like Content-length < 100) similarly as the ones having no body, but this requirers `async with` again.

On the flip side, does `async with` have a timeout? What happens if you put `async with session.get()` into a `wait_for` and timeout reached in exit?

The last question is a little bit more cumbersome than it looks like. The first important thing is: it should be **safe to interrupt every coroutine** at any time, right? I mean you may want to wrap it with `wait_for` or any other cancellation thing and expect it to work. So the question might be like "if it's safe to interrupt in exit, the thing might have `async with` otherwise it requires to have `with`". Except, off the top of my head there is not much good scenarious where `__aexit__` is safe. So the new useful pattern might be:

```
def __await__:
    with self:
        ...
```

**Comment by fafhrd91** [comment]
i modified `release()` to close connection instead of consuming data.
but we should keep both functions as intention is different.
