### ISSUE TITLE
aiohttp should attempt to calculate FormData's Content-Length

### ISSUE THREAD

**Issue by Kentzo** [aio-libs/aiohttp#867]
## Long story short

It would be convenient if aiohttp tried to calculate length of a form and set `Content-Length` manually.
## Expected behaviour

Requests sending FormData should calculate and set `Content-Length` whenever possible.
## Actual behaviour

`Content-Length` is left unset.

**Comment by Kentzo** [comment]
It appears that multipart uploads can only be sent as chunked. Unfortunately that's not supported by the server. Is there a workaround for that?

**Comment by fafhrd91** [comment]
If you know size of payload then it is easy. Just specify concern-length

**Comment by fafhrd91** [comment]
Maybe in some specific use case that makes sense but we assume then payload size is not knowen

**Comment by Kentzo** [comment]
@fafhrd91 `aiohttp` drops Content-Length header if present for chunked uploads.

**Comment by fafhrd91** [comment]
@Kentzo could you provide test case?

**Comment by Kentzo** [comment]
@fafhrd91 what kind of test case? an example of a web service that require Content-Length for FormData?

**Comment by Kentzo** [comment]
If anyone is interested, it was [HockeyApp](http://hockeyapp.net).

**Comment by Kentzo** [comment]
@asvetlov What do you think, does this request make sense?

**Comment by asvetlov** [comment]
Yes, I think it makes sense.
Unfortunately I have no free time to work on the issue, sorry.
But if you'll produce a PR I'd love to merge it.
Review by @kxepal is very appreciated.

**Comment by alexhayes** [comment]
@fafhrd91 I don't believe it's as simple as setting `Content-Length` header because there are a number of things that are happening internally with the content, for instance, gzip, the boundary etc.. So it's up to aiohttp internally to set this.

**Comment by asvetlov** [comment]
The issue is waiting for volunteer.

**Comment by alexhayes** [comment]
I'll be having a go shortly - just preparing another PR for a separate issue.

**Comment by alexhayes** [comment]
After looking into this further I'm not convinced that aiohttp is doing the wrong thing. It looks to me that this is by design that it's not setting the `Content-Length` because it's being chunked. However, if we compare this to `requests`, it does set `Content-Length` for FormData (at least with file uploads).

So I guess my question to @asvetlov would be, should `FormData` with a file upload (ie.. `multipart=True`) always be chunked? Should there be a way of turning off chunk'ing? 

I note that `requests` doesn't automatically chunk when there is `FormData` and a file - it does the following;

``` python
chunked = not (request.body is None or 'Content-Length' in request.headers)
```

Would something like the above be desirable in `aiohttp`?

Note, that if you really need to set the `Content-Length` header you can do so as follows;

``` python
content = """
foo bar
"""

with aiohttp.MultipartWriter('form-data') as mpwriter:
    part = mpwriter.append(io.BytesIO(content), {'CONTENT-TYPE': 'text/plain'})
    part.set_content_disposition('form-data', filename='foo.txt', name='file')
body = b''.join(mpwriter.serialize())

async with session.post(
                        'http://awesome-server.com/upload',
                        data=body,
                        headers=mpwriter.headers,
                        ) as resp:
    ...
```

This will cause the chunking to be turned off.

**Comment by kxepal** [comment]
We may have lazy Content-Length setting by analyzing multipart body(-ies). If we can surely say what content length will be at the serialize call, then set. Otherwise - skip.

**Comment by asvetlov** [comment]
Sounds good.

**Comment by Kentzo** [comment]
Is it still a problem?

**Comment by fafhrd91** [comment]
let's discuss all options in #1172
