### ISSUE TITLE
StreamReader.read(n) to read n bytes or until eof

### ISSUE THREAD

**Issue by foobarna** [aio-libs/aiohttp#959]
when doing `response.content.read(n)` it yields how many bytes are in the buffer, instead of waiting for the n bytes
in order to wait for them i have to keep the CPU busy, by doing something like this https://gist.github.com/foobarna/19c132304e140bf5031c273f6dc27ece

I know that `StreamReader.read()` from `asyncio` specifies this in the doc, but having your enhanced version of it, wouldn't it be better to wait for the desired size and only then yield?

by doing the above, `requests` and `urllib3` (with `stream=True` and 'preload_content=False`, respectively)  are doing better in terms of CPU time spent and memory usage for a file of 10 GB

[requests stream](http://docs.python-requests.org/en/master/api/?highlight=read#requests.Response.iter_content)
[urllib3 stream](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#streaming-and-io)

**Comment by fafhrd91** [comment]
use `readexactly` instead

**Comment by foobarna** [comment]
i've tested the `readexactly` but still had the deficit in CPU/memory use and that is because `readexactly` does exactly what i've been doing

**Comment by fafhrd91** [comment]
Would you mind to make PR?

**Comment by foobarna** [comment]
would like to make a PR, but i don't have the time right now for it (maybe in the near future)
was thinking that for one with knowledge about the code would be a quick fix

**Comment by asvetlov** [comment]
There is nothing for free.
Asynchronous API has no method for reading exactly requested amount of bytes at C level.

It means Python code should collect received data chunk by chunk in order of receiving.
That's exactly what `stream.readexactly()` does.

Synchronous API is a little different, it processes buffer operations on C level. That's why you see lower CPU usage for `requests` library.

Maybe Cython optimizations for aiohttp.streams may help but they are out of scope of the issue.
