### ISSUE TITLE
Change connector's limit parameter

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/aiohttp#977]
Now it is `None` by default (infinite amount of parallel connections).

I suggest shrinking the default to large enough but limited value.

The main question is: what the value should be? 10? 100? 1000?
The only thought about default: it should correlate with default number of available file descriptors, which is 1024.

Thus we have a choice between 10-50-100.

Any suggestions?

**Comment by ludovic-gasc** [comment]
Maybe we could have 900 as default value to be safe, and a warning message when the limit is reached ?
To help the users to spot the bottlenecks. It should be sad they use Go only because they don't change this value.

**Comment by tailhook** [comment]
> Maybe we could have 900 as default value to be safe

It's not too safe because the limit is applied on a single host (right?). And there is no limit on number of hosts you can connect using a single session and a number of sessions you can create.

So I would prefer something at the order of 10 (In fact I would prefer exactly `1` by default, but it's not an easy thing to cope with for most users)

**Comment by rmariano** [comment]
As agreed with @asvetlov , I will start setting up a limit of 20 connections by default, but letting this to be changed by passing a new parameter.

**Comment by asvetlov** [comment]
Fixed by #991
